### ISSUE TITLE
Why the distillation loss in LwF is different from the loss function in original paper.

### ISSUE THREAD

**Issue by WenjinW** [ContinualAI/avalanche#1014]
Hi, thanks for your contributions to the continual learning community. When I tried to use the avalanche, I encountered the following difficulties, and I am very grateful for your help.

I find that the implementation of the distillation loss is not consistent with the original paper, is there any special consideration?

The loss in the original paper is as follows:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/30342227/167249967-656b2f4b-da41-4566-aac2-72073cb52105.png">

The implementation of loss in the avalanche is as follows:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/30342227/167250025-e1dd27cf-754a-4d11-b13f-ac10b2386626.png">

**Comment by AntonioCarta** [comment]
How is it different from the original paper? Apart from some implementation details (like `active_units`) they should be the same.

**Comment by WenjinW** [comment]
Thanks for your reply, now I understand their equivalence.
