### ISSUE TITLE
Multi task LwF

### ISSUE THREAD

**Issue by guy-oren** [ContinualAI/avalanche#1026]
First, let me thank you for the effort and contributions to the community. 

Recently, I have been doing a research related to the LwF in the multi task scenario (task incremental) and I found that LwF performance is on par with SOTA methods, link: https://openaccess.thecvf.com/content/ICCV2021W/DeepMTL/papers/Oren_In_Defense_of_the_Learning_Without_Forgetting_for_Task_Incremental_ICCVW_2021_paper.pdf

However, in the API documentation I found that the method is not using the task labels. Although, LwF can be fitted to class incremental scenario, the naive fit is far from SOTA methods. The point is, if the intention is to formulate the way researchers are doing continual learning research I think it is better to make the method use task labels by default, or at least mention it in some way. 

Thanks for the great work

**Comment by AntonioCarta** [comment]
The documentation here is a bit misleading. Multi task LwF does work in the master branch, you need to use a model with a `MultiHeadClassifier`.
