### ISSUE TITLE
Reproducibility of Results

### ISSUE THREAD

**Issue by hsalkhatib** [ContinualAI/avalanche#1038]
I ran the "Comprehensive Example" [https://avalanche.continualai.org/from-zero-to-hero-tutorial/07_putting-all-together#a-comprehensive-example](url), and the example produce different accuracy results with every run. 
Is there an option to use a seed that will make results reproducible?

**Comment by AndreaCossu** [comment]
You can fix the seed at the beginning of the script like recommended by PyTorch for reproducibility. You can additionally pass the seed to the benchmark to ensure the stream stays the same. That should be enough :smile:

**Comment by hsalkhatib** [comment]
Thank you again Andrea for your quick responses.
