### ISSUE TITLE
Error while loading minibatch

### ISSUE THREAD

**Issue by PabloMese** [ContinualAI/avalanche#1044]
Hi everyone

What is the function `__getitem__(self, idx)` in class `ClassificationSubset` of file [dataset_utils.py](https://github.com/ContinualAI/avalanche/blob/f56ce189627effbb7b82bec5403326c9294027cf/avalanche/benchmarks/utils/dataset_utils.py#L243) supposed to return? Because I'm getting an error when indexing the `results` variable because value in position 1 is not an integer.

**Comment by AntonioCarta** [comment]
Classification datasets in Avalanche return triplets <x, y, t>, where x is the input, y, the label (integer), t the task label (integer, possibly fixed to 0 if task labels are not available).

**Comment by PabloMese** [comment]
I'm working on a Multiple Instance Framework and I'm having troubles to load correctly the data. I got my Dataset and an iterable object for loading minibatches. How do you suggest to introduce this into Avalanche? Thank you very much

**Comment by AndreaCossu** [comment]
For the `AvalancheDataset` you can define a custom `collate_fn` function which is used when slicing the dataset to stack more than 1 sample. Maybe you can build the `AvalancheDataset` out of your `Dataset` and then put the iterable object's logics inside the `collate_fn`.
