### ISSUE TITLE
ADD methods to apidoc

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#1061]
We would like to have methods documented in the apidoc. The main roadblock right now is that the doc building is killed due to excessive time/memory consumption.

See #1059

**Comment by lrzpellegrini** [comment]
I just tested adding the -j auto option in the docs Makefile as follows:

```
SPHINXOPTS    = -j auto
```

This greatly speeds up things! I may try adding a new commit to #1059 and see if it works...

**Comment by AntonioCarta** [comment]
closing this since it ended up being too slow for rtd
