### ISSUE TITLE
AvalancheSubset does not replace original transformations

### ISSUE THREAD

**Issue by HamedHemati** [ContinualAI/avalanche#1083]
When creating a subset of a dataset using `AvalancheSubset` with a new tranform, the old (original) transform is not replaced with the new one, but instead, the new transform seems to be concatenated to the original transform. Here is a simple example code to reproduce the issue:

```python
# Create a simple tensor dataset (all tensors are initialized with ones)
x_data = torch.ones(100, 50)
y_data = torch.randint(0, 5, (100,))
torch_dataset = TensorDataset(x_data, y_data)

# Initialize AVL dataset -> transform: multiplies each tensor by 2
t_mult = lambda x: x * 2
transform_original = transforms.Compose([t_mult])
ds_original = AvalancheDataset(torch_dataset, transform=transform_original)

# Create a subset of the original dataset with new transformation (adds 0.1 to each tensor)
t_add = lambda x: x + 0.1
transform_subset = transforms.Compose([t_add])
subset_ind = torch.LongTensor(list(range(20)))
ds_subset = AvalancheSubset(ds_original, subset_ind, transform=transform_subset)

```
Now if we print `ds_subset[0]`, the input tensor values should be 1.1, but we get 2.1:

Input: 
```
print(ds_subset[0])
```

Output:
```
(tensor([2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000,
         2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000,
         2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000,
         2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000,
         2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000,
         2.1000, 2.1000, 2.1000, 2.1000, 2.1000]),
 tensor(4),
 0)
```

**Comment by AntonioCarta** [comment]
Is this a bug? I would expect transformations to compose together, not to replace each other.
@lrzpellegrini what is the expected behavior here?

**Comment by HamedHemati** [comment]
There are cases where you need to assign a new set of transformations to a subset of an existing dataset and concatenating would not be possible (because of the order in the transformation list). IMO assigning transformations would make things easier in general. Composing them can be done manually first and then assigned for the subset.

**Comment by AntonioCarta** [comment]
I understand that this is a reasonable use case, but I think we already cover it. Can you use `replace_transform` to do this?
