### ISSUE TITLE
JointTraining strategy does not shuffle the whole dataset when picking minibatch

### ISSUE THREAD

**Issue by ema-marconato** [ContinualAI/avalanche#1094]
So I noticed that when calling JointTraining on a `dataset_benchmark` the mini-batches are not iid w.r.t. the whole datasets. Any clue on how to solve the issue?

**Comment by AndreaCossu** [comment]
From a quick look at the code I think the mini-batches should be shuffled since `shuffle=True` by default in the dataloader creation. Can you please provide a quick script to verify your results? I can start from there and help you out :smile:

**Comment by AntonioCarta** [comment]
closing this since it doesn't look like an avalanche bug and we cannot reproduce it.
