### ISSUE TITLE
in EWC the penalty is 0

### ISSUE THREAD

**Issue by matkowski-voy** [ContinualAI/avalanche#1099]
🐛 **Describe the bug**
Currently in [EWC ](https://github.com/ContinualAI/avalanche/blob/master/avalanche/training/plugins/ewc.py)plugin the penalty is always 0 
```
n_units = saved_param.shape[0]
cur_param = saved_param[:n_units]
penalty += (imp * (cur_param - saved_param).pow(2)).sum()
```

because `cur_param` is equal to `saved_param` in the penalty from computation `penalty += (imp * (cur_param - saved_param).pow(2)).sum()`

**Comment by AntonioCarta** [comment]
you are right. It should be `cur_param = cur_param[:n_units]`

**Comment by AndreaCossu** [comment]
We need to fix this and make a new release asap
