### ISSUE TITLE
Storing all evaluation scores for each epoch in an experience in CSVLogger

### ISSUE THREAD

**Issue by dalbertweiss** [ContinualAI/avalanche#1103]
Hi together, 
my aim is to reproduce the phenomena of catastrophic forgetting. This is also something I was able to reproduce or see when logging the results to CSVLogger. Here you see quite nicely that the metric scores goes down again while the loss goes up for dataset1 while the loss is going up again.

However, if I see it corretly ```eval_results``` only stores the evaluation scores for the last epoch (after running all experiences). Is there a possibility to store all evaluation scores for each epoch of each experience? My aim is to plot the classical plot where you see the loss for dataset 1 increasing again when training in experience2.

**Comment by AndreaCossu** [comment]
Hi @dalbertweiss, consider that if you use the `TensorboardLogger` and monitor the epoch accuracy you have the plot you mention for free. If you want to make a custom one, I would recommend to use the metric dictionaries returned by the train and eval methods which contain all the metrics computed during the execution of that method. 
You can always access all the metrics computed so far by calling `eval_plugin.get_all_metrics()`. Check out the [from zero to hero tutorial - Evaluation](https://avalanche.continualai.org/from-zero-to-hero-tutorial/05_evaluation) for more info.

**Comment by dalbertweiss** [comment]
Perfect that was exactly what I was looking for!
