### ISSUE TITLE
`classes_in_experience` doesn't return an unique set of tensors

### ISSUE THREAD

**Issue by DWarez** [ContinualAI/avalanche#1104]
🐛 **Describe the bug**
As the title says, the property `classes_in_experience` of the class `GenericCLScenario` doesn't return an set of unique tensors containing 
the labels of the experience's patterns. Instead, the set contains ALL the tensors of the experience's patterns. 

🐜 **To Reproduce**
I cannot provide the exact code that generates the bug because it's under a NDA. I will try to obtain a MWE as soon as I can.

🐝 **Expected behavior**
The expected output is a set containing one tensor per each class in the experience, containing the classes' labels.

🐞 **Screenshots**
[Debugging output](https://canada1.discourse-cdn.com/free1/uploads/continualai/original/1X/745c3afdddcc1c8bade214af434e6d897302e75d.png)

🦋 **Additional context**
Python version: 3.8.12
Avalanche version: 0.2.0
[Forum discussion](https://continualai.discourse.group/t/how-to-extract-class-labels-from-genericclscenario-class/374/4)

**Comment by AntonioCarta** [comment]
@lrzpellegrini can you check this? maybe your last changes fixed it.
