### ISSUE TITLE
LwF under performs

### ISSUE THREAD

**Issue by tachyonicClock** [ContinualAI/avalanche#1115]
🐛 **Describe the bug**
After struggling to tune LwF to perform better than naive in my experiments I decided to validate that LwF worked at all. I discovered that LwF appears to be broken. I'm not having much luck fixing it and was wondering if anyone has any ideas.

```
# in https://github.com/ContinualAI/continual-learning-baselines
======================================================================
FAIL: test_smnist (tests.lwf.experiment.LwF)
Split MNIST benchmark
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Scratch/al183/continual-learning-baselines/tests/lwf/experiment.py", line 33, in test_smnist
    self.assertAlmostEqual(target_acc, avg_stream_acc, delta=0.03)
AssertionError: 0.31 != 0.1944 within 0.03 delta (0.11560000000000001 difference)

----------------------------------------------------------------------
```

Since I don't think https://github.com/ContinualAI/continual-learning-baselines is particularly actively maintained, I tried the LwF example in avalanche. I found that it also performed less than I would expect with an accuracy of  `0.2078`. 

🐜 **To Reproduce**
```
# in https://github.com/ContinualAI/continual-learning-baselines
python -m unittest tests.LwF.test_smnist
```
or
```
# in https://github.com/ContinualAI/avalanche
python3 examples/lwf_mnist.py
```

Both have a final accuracy of roughly `0.2 but I would expect an accuracy of 0.3 according to https://github.com/ContinualAI/continual-learning-baselines.

🐝 **Expected behavior**
LwF on smnist should have an accuracy of approximately `0.3`

**Comment by AndreaCossu** [comment]
Hi @tachyonicClock , which version of Avalanche are you using?

**Comment by tachyonicClock** [comment]
The most recent version. I pulled from master

**Comment by AndreaCossu** [comment]
Ok thanks, I will take a look at that and keep you updated!

**Comment by AndreaCossu** [comment]
@tachyonicClock LwF performs on par with the paper above if the LwF penalization grows over time and the cross-entropy contribution diminishes over time. Since this is not a LwF dependant choice, in the continual-baselines we did not add the cross-entropy weighting. Adding it closes the gap with the expected performance. Let me know if you have any further questions :smile:

**Comment by tachyonicClock** [comment]
Huge thanks for getting back to me so quickly. Not quite the answer I was hoping for, but it is what it is :D
