### ISSUE TITLE
evaluation metric compute wrong average accuracies?

### ISSUE THREAD

**Issue by 3koozy** [ContinualAI/avalanche#1137]
🐛 **Describe the bug**
during several experiments, I have noticed some strange log files like below, where individual per experience evaluation accuracy is computed but computes the wrong average :
-----------------------------------------------------------------------------------------------------------
-- >> Start of eval phase << --
-- Starting eval on experience 0 (Task 0) from test stream --
> Eval on experience 0 (Task 0) from test stream ended.
	ExperienceForgetting/eval_phase/test_stream/Task000/Exp000 = 0.4470
	Loss_Exp/eval_phase/test_stream/Task000/Exp000 = 2.5918
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp000 = **0.5391**
-- Starting eval on experience 1 (Task 0) from test stream --
> Eval on experience 1 (Task 0) from test stream ended.
	ExperienceForgetting/eval_phase/test_stream/Task000/Exp001 = 0.4777
	Loss_Exp/eval_phase/test_stream/Task000/Exp001 = 2.7891
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp001 = **0.5005**
-- Starting eval on experience 2 (Task 0) from test stream --
> Eval on experience 2 (Task 0) from test stream ended.
	ExperienceForgetting/eval_phase/test_stream/Task000/Exp002 = 0.6892
	Loss_Exp/eval_phase/test_stream/Task000/Exp002 = 4.7731
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp002 = **0.2843**
-- Starting eval on experience 3 (Task 0) from test stream --
> Eval on experience 3 (Task 0) from test stream ended.
	ExperienceForgetting/eval_phase/test_stream/Task000/Exp003 = 0.4703
	Loss_Exp/eval_phase/test_stream/Task000/Exp003 = 3.2605
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp003 = **0.5102**
-- Starting eval on experience 4 (Task 0) from test stream --
> Eval on experience 4 (Task 0) from test stream ended.
	ExperienceForgetting/eval_phase/test_stream/Task000/Exp004 = 0.4262
	Loss_Exp/eval_phase/test_stream/Task000/Exp004 = 2.3445
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp004 = **0.5277**
-- Starting eval on experience 5 (Task 0) from test stream --
> Eval on experience 5 (Task 0) from test stream ended.
	ExperienceForgetting/eval_phase/test_stream/Task000/Exp005 = 0.4622
	Loss_Exp/eval_phase/test_stream/Task000/Exp005 = 2.3979
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp005 = **0.4653**
-- Starting eval on experience 6 (Task 0) from test stream --
> Eval on experience 6 (Task 0) from test stream ended.
	Loss_Exp/eval_phase/test_stream/Task000/Exp006 = 0.0994
	Top1_Acc_Exp/eval_phase/test_stream/Task000/Exp006 = **0.9736**
-- >> End of eval phase << --
	Accuracy_On_Trained_Experiences/eval_phase/test_stream/Task000 = 0.5048
	ConfusionMatrix_Stream/eval_phase/test_stream = <avalanche.evaluation.metric_results.AlternativeValues object at 0x7effe45ac550>
	Loss_Stream/eval_phase/test_stream/Task000 = 2.8382
	StreamForgetting/eval_phase/test_stream = 0.4954
	Top1_Acc_Stream/eval_phase/test_stream/Task000 = **_0.5048_**
----------------------------------------------------------------------------------------------------------------------
average accuracy should be : 0.5429 not 0.5048.
am i I missing something here?

🐜 **To Reproduce**
A [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) to reproduce the issue. The code should be executable without modifications.

🐝 **Expected behavior**

🐞 **Screenshots**

🦋 **Additional context**
Add any other context about the problem here like your python setup.

**Comment by AntonioCarta** [comment]
The average is over the samples of the entire stream. As a result, if the experiences have different size, averaging the experience average accuracy returns a different result.

**Comment by 3koozy** [comment]
thx , as simple as it sounds this seems to explain it :)

**Comment by loukasilias** [comment]
Hello,

How can I access the confusion matrix?

`ConfusionMatrix_Stream/eval_phase/test_stream = <avalanche.evaluation.metric_results.AlternativeValues object at 0x7effe45ac550>
`
