### ISSUE TITLE
unable to assign different learning rates to different param_groups in an optimizer

### ISSUE THREAD

**Issue by 3koozy** [ContinualAI/avalanche#1145]
🐛 **Describe the bug**
Hello guys, I hope you're having a wonderful day :).
I tried assigning multiple learning rates onto different param_groups in an optimizer, but I was unable to run it due to avalanche built-in assert :

```
[/usr/local/lib/python3.7/dist-packages/avalanche/training/templates/base_sgd.py](https://localhost:8080/#) in _before_training_exp(self, **kwargs)
    150         # Model Adaptation (e.g. freeze/add new units)
    151         self.model = self.model_adaptation()
--> 152         self.make_optimizer()
    153         super()._before_training_exp(**kwargs)
    154 

[/usr/local/lib/python3.7/dist-packages/avalanche/training/templates/supervised.py](https://localhost:8080/#) in make_optimizer(self)
    293         # This allows to add new parameters (new heads) and
    294         # freezing old units during the model's adaptation phase.
--> 295         reset_optimizer(self.optimizer, self.model)
    296 
    297     #########################################################

[/usr/local/lib/python3.7/dist-packages/avalanche/models/dynamic_optimizers.py](https://localhost:8080/#) in reset_optimizer(optimizer, model)
     28     :return:
     29     """
---> 30     assert len(optimizer.param_groups) == 1
     31     optimizer.state = defaultdict(dict)
     32     optimizer.param_groups[0]["params"] = list(model.parameters())

AssertionError:
```

is there a specific reason why this assertion was put in place ? and if so, how can we assign different lr for different params_groups ?
my use case is basically to fine-tune a pre-trained model and use lr=0.0001 for feature extraction, then lr=0.001 for fc/classifier part for faster convergence.

Regards.

**Comment by AntonioCarta** [comment]
In short, the assert is there to warn you that you should implement your own `reset_optimizer`. By default, `reset_optimizer` makes some assumptions about the param groups, but if you have multiple param groups, you probably want to make your own decision.

Admittedly, we should make the warning nicer.
