### ISSUE TITLE
.train() should support a single eval stream

### ISSUE THREAD

**Issue by BenCrulis** [ContinualAI/avalanche#1156]
I'm trying to make the JointTraining strategy automatically evaluate the model on the test stream at the end of every epoch.

🐛 **Describe the bug**
The call to `joint_train.train` crashed with a `TypeError: 'ClassificationStream' object does not support item assignment`

🐜 **To Reproduce**
```python
from torch.nn import CrossEntropyLoss
from torch.optim import SGD

from avalanche.benchmarks.classic import PermutedMNIST
from avalanche.models import SimpleMLP
from avalanche.training.supervised import JointTraining

model = SimpleMLP(num_classes=10)

perm_mnist = PermutedMNIST(n_experiences=5)

optimizer = SGD(model.parameters(), lr=0.001, momentum=0.9)
criterion = CrossEntropyLoss()

joint_train = JointTraining(
    model,
    optimizer,
    criterion,
    train_mb_size=32,
    train_epochs=1,
    eval_mb_size=32,
    eval_every=1
)

joint_train.train(perm_mnist.train_stream, perm_mnist.test_stream)
```

🐝 **Expected behavior**
I'm expecting the `.train()` method to automatically evaluate the model on the test stream at the end of every epoch as the API suggests it can just take `perm_mnist.test_stream` just like it can take `perm_mnist.train_stream` as an argument.

🐞 **Screenshots**
```
Traceback (most recent call last):
  File "C:\Users\crulis\PycharmProjects\continual\mwe.py", line 25, in <module>
    joint_train.train(perm_mnist.train_stream, perm_mnist.test_stream)
  File "C:\Users\crulis\PycharmProjects\continual\venv10\lib\site-packages\avalanche\training\supervised\joint_training.py", line 135, in train
    eval_streams[i] = [exp]
TypeError: 'ClassificationStream' object does not support item assignment
```

I noticed that replacing `joint_train.train(perm_mnist.train_stream, perm_mnist.test_stream)` with `joint_train.train(perm_mnist.train_stream, [perm_mnist.test_stream])` appears to fix the crash, but this isn't intuitive and I don't know if the intended behavior ensues.

**Comment by AntonioCarta** [comment]
In general `train` expects a list of streams so that you can do `strategy.train(train_stream, [train_stream, valid_stream])` to eval both on training and validation streams. 

I'll leave this open because I think we can add support for the single stream too.
