### ISSUE TITLE
Small error in the demo

### ISSUE THREAD

**Issue by WenjinW** [ContinualAI/avalanche#1158]
🐛 **Describe the bug**
The "scenario" should be modified to "benchmark" for running the demo in [Putting all Together](https://avalanche.continualai.org/getting-started/learn-avalanche-in-5-minutes#putting-all-together) successfully.
![image](https://user-images.githubusercontent.com/30342227/196906729-4eb3b79d-3a86-4929-9102-3380b815a588.png)

**Comment by AntonioCarta** [comment]
Thanks. Fixed it.
