### ISSUE TITLE
 OnlineCLExperience has no attribute classes_in_this_experience

### ISSUE THREAD

**Issue by AlbinSou** [ContinualAI/avalanche#1197]
🐛 **Describe the bug**

When using online strategies, an error occurs in IncrementalClassifier model adaptation,

The error in question:

```
AttributeError: OnlineCLExperience has no attribute classes_in_this_experience
avalanche/models/dynamic_modules.py, line 233 in adaptation
```

🐜 **To Reproduce**

```{python}

#!/usr/bin/env python3
import numpy as np
import torch
from torch.optim import SGD

from avalanche.benchmarks.classic import SplitCIFAR10
from avalanche.benchmarks.scenarios.online_scenario import OnlineCLScenario
from avalanche.evaluation.metrics import accuracy_metrics, loss_metrics
from avalanche.logging import InteractiveLogger
from avalanche.models import SlimResNet18
from avalanche.training.plugins import EvaluationPlugin, ReplayPlugin
from avalanche.training.supervised import Naive
from avalanche.models.dynamic_modules import IncrementalClassifier

def main():
    fixed_class_order = np.arange(10)
    scenario = SplitCIFAR10(
        5,
        return_task_id=False,
        seed=0,
        fixed_class_order=fixed_class_order,
        shuffle=True,
        class_ids_from_zero_in_each_exp=False,
        dataset_root="/DATA/data/"
    )

    input_size = (3, 32, 32) 

    model = SlimResNet18(1)
    model.linear = IncrementalClassifier(model.linear.in_features, 1)

    optimizer = SGD(model.parameters(), lr=0.1)

    interactive_logger = InteractiveLogger()

    loggers = [interactive_logger]

    training_metrics = []

    evaluation_metrics = [
        accuracy_metrics(epoch=True, stream=True),
        loss_metrics(epoch=True, stream=True),
    ]

    # Create main evaluator that will be used by the training actor
    evaluator = EvaluationPlugin(
        *training_metrics,
        *evaluation_metrics,
        loggers=loggers,
    )

    plugins = [ReplayPlugin(2000)]

    device = torch.device("cuda")

    #######################
    #  Strategy Creation  #
    #######################

    cl_strategy = Naive(
        model=model,
        optimizer=optimizer,
        plugins=plugins,
        evaluator=evaluator,
        device=device,
        train_mb_size=64,
        eval_mb_size=64,
        eval_every=-1,
        peval_mode="epoch",
    )

    ###################
    #  TRAINING LOOP  #
    ###################

    print("Starting experiment...")
    results = []

    # For online scenario
    batch_streams = scenario.streams.values()

    for t, experience in enumerate(scenario.train_stream):
        print("Start of experience: ", experience.current_experience)
        print("Current Classes: ", experience.classes_in_this_experience)

        ocl_scenario = OnlineCLScenario(
            original_streams=batch_streams,
            experiences=experience,
            experience_size=32,
            access_task_boundaries=False,
        )

        cl_strategy.train(
            ocl_scenario.train_stream,
            eval_streams=[],
            num_workers=4,
        )

    # Only evaluate at the end on the test stream
    results.append(cl_strategy.eval(scenario.test_stream))

    return results


if __name__ == "__main__":
    main()

```

🐝 **Expected behavior**
In previous versions (idk which commit exactly made it fail), this attribute was existing both for normal and online experiences. The same code works fine with non-online experiences in the current version.

**Comment by AntonioCarta** [comment]
Thanks for reporting the issue. We have to fix this. I was thinking about providing some simple wrapper like `as_multitask/as_supervised` to add the necessary attributes to barebone experiences which only have the dataset. This way, users can also change the benchmark with simple operations (like going from task-agnostic to task-aware).

**Comment by AlbinSou** [comment]
@AntonioCarta 

Do you think adding a classes_in_this_experience property to OnlineCLExperience could be a temporary fix ?

I really think this is a bug because this currently prevents the use of DynamicModules that use this attribute in combination with an Online setting.

**Comment by HamedHemati** [comment]
@AlbinSou The tricky part about adding the `classes_in_this_experience` attribute in OCL experiences is that each sub-experience might contain only a subset of the classes from the original experience.  So we either need to include all classes from the original experience in each sub-experience and assign them to `classes_in_this_experience` which would not be correct, or add a new attribute like `classes_in_the_super_experience` and check the experience type when adapting the dynamic modules. 
What do you think @AntonioCarta ?

**Comment by AntonioCarta** [comment]
We can add `classes_in_this_experience ` as @AlbinSou suggests. As @HamedHemati is saying, we cannot copy the attribute from the original exp but we need to recompute it. Fortunately, computing it from the dataset should be cheap.

My preferred solution is to add a function `as_supervised` that given an experience with a `dataset` attribute adds all the necessary attribute for supervised tasks. This is very easy to add and allow us to use OCL generators for non-supervised tasks.

**Comment by AntonioCarta** [comment]
> My point is that, If the goal is also to support multi-head models, since classes_in_this_experience contains only the classes from the current sub-experience, the size of the new head will be equivalent to the number of classes seen in the first sub-experience. So for the next sub-experience, if new classes appear from the same (origin) experience, there can be an output size mismatch. So, in that case we would need to adapt the model for sub-experiences not only once, but whenever there are new classes in the new sub-experiences of each experience which can become expensive.

This is wrong. At the next sub-experience the model must be adapted again, adding the new classes.

**Comment by AntonioCarta** [comment]
> Ok, I thought we were adapting only at the task boundaries (first sub-experiences) for efficiency reasons.

Adapting is already efficient and negligible in terms of performance. If it's not, it's the method fault.
btw, this is why I think splitting OCL/batch templates is not necessarily a good thing. Each time it forces us to think about OCL as if it is a special case, which is really not in avalanche.

**Comment by HamedHemati** [comment]
Currently, the only difference is in resetting/updating the optimizers. We can merge them if you think that separation is confusing.

**Comment by HamedHemati** [comment]
I have updated the `OnlineObservation` class in #1297 . Now it adapts the model and resets the optimizer only at the boundary sub-experiences, and it expects `access_task_boundaries=True` when creating the OCL benchmark for a multi-head model.

```
ocl_benchmark = OnlineCLScenario(
            original_streams=batch_streams, experiences=exp, experience_size=10,
            access_task_boundaries=True
        )
```

I tested it with MTSimpleMLP, and it worked fine.

For regular models, the optimizer is not reset/updated as it does not expect changes in the parameter size.

**Comment by AlbinSou** [comment]
> I have updated the `OnlineObservation` class in #1297 . Now it adapts the model and resets the optimizer only at the boundary sub-experiences, and it expects `access_task_boundaries=True` when creating the OCL benchmark for a multi-head model.
> 
> ```
> ocl_benchmark = OnlineCLScenario(
>             original_streams=batch_streams, experiences=exp, experience_size=10,
>             access_task_boundaries=True
>         )
> ```
> 
> I tested it with MTSimpleMLP, and it worked fine.
> 
> For regular models, the optimizer is not reset/updated as it does not expect changes in the parameter size.
> 
> *Regarding the attribute access issue, when `access_task_boundaries=True`, model adaptation works with: `avalanche_model_adaptation(model, self.experience.origin_experience)` at the boundaries sub-experiences.

Great @HamedHemati, thanks for the changes !

Regarding the class-incremental setting in online learning, I think there is still a slight problem. Ideally we also want to use an IncrementalClassifier as well in that setting, but also be free to not use boundary access, my previous suggestion was that the optimizer should be adapted at every sub-experience (as it is already the case and also what you suggest), but that the classes_in_this_experience attribute should contain only classes inside the sub-experience (mini-batch), instead of the ones in the original experience.

**Comment by HamedHemati** [comment]
@AlbinSou I see your point, but things may also get unnecessarily complicated as well. For example, if task 2 consists of classes {1,3,4,7}, and in the first sub-experience of task 2, we have classes {1,7}, the adapted head would already cover all experience classes and all adaptation checks would be unnecessary afterward. But if we have classes {1,3} in the first sub-experiences, then new neurons  (for classes 4 or 7) should be added, and that can happen at any step. This can become computationally expensive if the model size is large and `experience_size=1`. I'm also not sure if that would make a difference in terms of model's performance in the end. 

My main point is that we don't need model adaptation after each sub-experience for most online strategies especially if we have thousands of sub-experiences in each original experience. Even particular strategies that need to make manual adaptations at arbitrary steps can be implemented by sub-classing and manually checking adaptation according to a criterion.

**Comment by AntonioCarta** [comment]
> This can become computationally expensive if the model size is large and experience_size=1. 

Have you actually measured this overhead? I think it's almost zero.
We need to support dynamic modules also in the boundary-free setting.

As a related note, IMO there is a naming problem in the current templates. The online/batch observation templates are actually the boundary-free (batch) and boundary-aware (online). There is no difference between online and batch when you don't have boundaries.

**Comment by AlbinSou** [comment]
> @AlbinSou I see your point, but things may also get unnecessarily complicated as well. For example, if task 2 consists of classes {1,3,4,7}, and in the first sub-experience of task 2, we have classes {1,7}, the adapted head would already cover all experience classes and all adaptation checks would be unnecessary afterward. But if we have classes {1,3} in the first sub-experiences, then new neurons (for classes 4 or 7) should be added, and that can happen at any step. This can become computationally expensive if the model size is large and `experience_size=1`. I'm also not sure if that would make a difference in terms of model's performance in the end.
> 
> My main point is that we don't need model adaptation after each sub-experience for most online strategies especially if we have thousands of sub-experiences in each original experience. Even particular strategies that need to make manual adaptations at arbitrary steps can be implemented by sub-classing and manually checking adaptation according to a criterion.
> 
> ** We can still add the `classes_in_this_experience` attribute for each sub-exp as well. That's a different point.

Hmm, this is true, but I think adapting should not be a big overhead if no new classes are seen. Also about what you mentioned on the class order, I forgot this behavior, I guess ideally we would want to initialize only 2 new logits instead of 6 when encountering classes 1 and 7. But this is not how things are handled right now and might be a hard change to make...

**Comment by AntonioCarta** [comment]
> Also about what you mentioned on the class order, I forgot this behavior, I guess ideally we would want to initialize only 2 new logits instead of 6 when encountering classes 1 and 7. But this is not how things are handled right now and might be a hard change to make...

About this point, we do use masking to avoid using the unseen output units.

**Comment by HamedHemati** [comment]
Thanks for the discussion. In the latest version I've added the attributes needed for model adaptation (`classes_in_this_experience` and `task_labels`) to sub-experiences, and also re-added the model adaptation step for online CL experiences without boundaries. 

> As a related note, IMO there is a naming problem in the current templates. The online/batch observation templates are actually the boundary-free (batch) and boundary-aware (online). There is no difference between online and batch when you don't have boundaries.

AFAIK the concept of task boundaries applies to online streams, and the current definition of online/batch observations defines that separation. Maybe other aspects could be considered for the separation, but for now it's only the task boundary. Let me know if I'm missing anything here.

> Have you actually measured this overhead? I think it's almost zero.

Actually I haven't tried it with large models, but I can assume it can have some unnecessary computational overhead in boundary-aware online scenarios when the number of parameters is high since `update_optimizer` has a for loop over the model's parameters.

**Comment by AntonioCarta** [comment]
> AFAIK the concept of task boundaries applies to online streams

This is what happens in the literature. Still, boundary-awareness and batch/online are orthogonal properties. You can have a batch scenario where you have multiple batches without shifts. In this setting, you may or may not know when the shift happens.

> Actually I haven't tried it with large models, but I can assume it can have some unnecessary computational overhead in boundary-aware online scenarios when the number of parameters is high since update_optimizer has a for loop over the model's parameters.

I'm not convinced that there is an overhead. There are no expensive operations in that loop.
If you measure the overhead and it turns out it is expensive, we will definitely fix it.

**Comment by AntonioCarta** [comment]
@AlbinSou is this fixed now?
