### ISSUE TITLE
Importance computation in EWC

### ISSUE THREAD

**Issue by nicobonne** [ContinualAI/avalanche#1224]
Hello! Thank you for your effort putting togheter this awesome library!

I was eperimenting with EWC and I noticed something odd in the computation of the importance:
https://github.com/ContinualAI/avalanche/blob/c1ca18d1c44f7cc8964686efd54a79443763d945/avalanche/training/plugins/ewc.py#L178-L180

The expected value is computed wrt the number of batches. Shouldn't it be divided by `len(dataset)` instead of `len(dataloader)`?

**Comment by AndreaCossu** [comment]
The importance is computed in mini-batches, not one sample at a time. Therefore, we divide for the number of minibatches, which is `len(dataloader)`.

**Comment by nicobonne** [comment]
Makes sense, thank you!
