### ISSUE TITLE
Clarification on the compatibility with PyTorch Lightning

### ISSUE THREAD

**Issue by bonpagnakann** [ContinualAI/avalanche#1231]
Hello authors. I would like to check with you whether Avalanche is also working with PyTorch Lightning framework if I want to contribute new experiments in the future. Thank you in advance for your response.

**Comment by AntonioCarta** [comment]
Currently avalanche strategies are not implemented using PyTorch Lightning. However, most components can be used within a Lightning Trainer, such as benchmarks, models, replay buffers, and some regularization losses. By using Lightning you lose the metrics and logging system (you can still use metrics but they become more verbose) and the plugin system.

If you have an example using Avalanche inside Lightning we can add it to the official examples.
