### ISSUE TITLE
torchmetrics v0.11 incompatiblity

### ISSUE THREAD

**Issue by 3koozy** [ContinualAI/avalanche#1232]
Hello guys :),
so just two days ago, torchmetrics relrease a new version V0.11 ([see here](https://pypi.org/project/torchmetrics/#history)) which redefined their class torchmetrics.functional.accuracy to require definition of task type (see link : [Click Here](https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html#accuracy)).

this causes an error to be raised when using accuracy metrics , since it uses accuracy class without defining task positional argument.
for now I managed to make my current code work by specifying the previous version of torchmetrics as follows:
`!pip install torchmetrics==0.10.3`

**Comment by lrzpellegrini** [comment]
Confirmed, very strange that this is not covered by unit tests...

Reproduced by:

```python
def test_topk_accuracy(self):
    metric = TopkAccuracy(5)
    self.assertEqual(metric.result(), {})
    metric.update(self.out, self.y, 0)

    self.assertLessEqual(metric.result()[0], 1)
    self.assertGreaterEqual(metric.result()[0], 0)
    metric.reset()
    self.assertEqual(metric.result(), {})
```

@scumatteo
