### ISSUE TITLE
Error importing from benchmarks

### ISSUE THREAD

**Issue by nathanaelg16** [ContinualAI/avalanche#1233]
🐛 **Describe the bug**
When importing from benchmarks, the following error is observed: `ImportError: cannot import name 'Kinetics400' from 'torchvision.datasets`

🐜 **To Reproduce**
```
from avalanche.benchmarks import GenericCLScenario, TCLExperience

def main():
    print("Hello, world!")

if __name__ == '__main__':
    main()
```

🐝 **Expected behavior**
The above program should print `Hello, world!`. However, an error occurs during the import statement.

🐞 **Screenshots**
![image](https://user-images.githubusercontent.com/12057936/205449889-cc8318b2-bb9d-4e4d-8280-3acef6f89a87.png)

🦋 **Additional context**
Python version: 3.9.15
Avalanche version: 0.2.1

This error still occurs in a new clean conda environment where the only packages installed are python and avalanche-lib (via pip), and avalanche-lib's dependencies.

**Comment by ChaceAshcraft** [comment]
Looks like the Kinetics dataset isn't in torchvision_wrapper.py anymore (https://github.com/ContinualAI/avalanche/blob/master/avalanche/benchmarks/datasets/torchvision_wrapper.py), but this change hasn't been pushed to the latest release. Installing directly from GitHub seemed to fix it.

https://avalanche.continualai.org/getting-started/how-to-install#install-the-master-branch-using-pip

**Comment by AntonioCarta** [comment]
Like @ChaceAshcraft is saying, we fixed this bug in the master. We are going to release avalanche 0.0.3 soon so it will also be fixed in the pip package.
