### ISSUE TITLE
ClassificationStream does not subclass CLStream

### ISSUE THREAD

**Issue by lrzpellegrini** [ContinualAI/avalanche#1241]
🐛 **Describe the bug**
The class `ClassificationStream` does not subclass `CLStream`. This gives type hint issues when passing entire streams to the train/eval methods of the strategies. This is an issue at the type checker level, it does not affect the ability to run the code correctly.

🐜 **To Reproduce**
The problem is reported by PyLance when using VSCode.

🐝 **Expected behavior**
Passing an entire stream to train/eval should not raise typing warnings.

🦋 **Additional context**
The CLStream class wants a constructor parameter `exps_iter`, but we are currently implementing `ClassificationStream` by t implementing `__len__` and `__getitem__`. The two things seem to be overlapping and not fully compatible.

**Comment by AntonioCarta** [comment]
@lrzpellegrini is this fixed?

**Comment by lrzpellegrini** [comment]
Yes, was fixed in #1333

Closing
