### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MagicHealer** [ContinualAI/avalanche#1267]
![image](https://user-images.githubusercontent.com/108260301/210708605-0c82c3f0-3b0e-4a76-bafc-a85c4aba63ca.png)

**Comment by vlomonaco** [comment]
Hi @MagicHealer! Thanks for reporting the issue. Can you give us more details about it?
Is this a notebook? which version of Avalanche are you using?

**Comment by MagicHealer** [comment]
@vlomonaco I was able to resolve the issue upon updating the version into 0.3.1 from 0.2.1. Thank you.
