### ISSUE TITLE
Checkpoint Example Not Working

### ISSUE THREAD

**Issue by wistuba** [ContinualAI/avalanche#1269]
I'm running https://github.com/ContinualAI/avalanche/blob/master/examples/checkpointing.py on a CPU using `python checkpointing.py --cuda -1` and observe `AttributeError: Can't pickle local object 'EmptyTransformGroups.__init__.<locals>.<lambda>'`. Removing `num_workers` solves the problem.

**Comment by Melika-Ayoughi** [comment]
I also get this error while checkpointing with icarl on cifar10:
NotImplementedError: ('{} cannot be pickled', '_MultiProcessingDataLoaderIter')
Is it related to the same issue? What is the workaround to fix it?
Best
