### ISSUE TITLE
Different transformation for incoming and memory data

### ISSUE THREAD

**Issue by wistuba** [ContinualAI/avalanche#1277]
I want to use a replay method and apply different transformations to replay data. I could not find an example and the documentation has something that seems to go in that direction but I don't see how this will work: https://avalanche.continualai.org/how-tos/avalanchedataset/avalanche-transformations#custom-transformation-groups

I basically want something like this where the replay transforms are actually used:
```
strategy = Naive(plugins=[replay_plugin], ...)
benchmark = dataset_benchmark(
    [train_dataset],
    [val_dataset],
    train_transform=train_transform,
    train_target_transform=train_target_transform,
    eval_transform=test_transform,
    eval_target_transform=test_target_transform,
    replay_transform=replay_transform,
    replay_target_transform=replay_target_transform,
)
train_exp = benchmark.train_stream[0]
strategy.train(train_exp)
```

**Comment by AntonioCarta** [comment]
Have you checked the [dataloading and replay](https://avalanche.continualai.org/how-tos/dataloading_buffers_replay) tutorial? Benchmarks and replay buffers are independent objects. You can manipulate the buffer datasets directly if you want to add transformations.

To change the transformations, you will probably have to do your own ReplayPlugin. You can start from Avalanche Replay Plugin and add the transformation to the buffer.

**Comment by wistuba** [comment]
Thanks, that might work.
