### ISSUE TITLE
About Replay Plugin, why is the same experience training slower and slower?

### ISSUE THREAD

**Issue by Xuxuduoyu** [ContinualAI/avalanche#1280]
🐛 **Describe the bug**
I use Replay plug-in training, in the same task, at the beginning of training an epoch for more than 3 minutes, later on more than 10 minutes, I would like to ask why? Is there a bug?  The training is the Ciffa100 data set, divided into 10 tasks, each task training 50 epochs.

🐜 **To Reproduce**
A [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) to reproduce the issue. The code should be executable without modifications.

🐝 **Expected behavior**
I personally think: different experience, training speed is not the same, is understandable. However, with different epochs of the same experience, why will the training speed get slower and slower?
🐞 **Screenshots**

![Uploading e96db5af3fe629647d0d9f3a55951ed.png…]()
![99f5747895174f8357b579c1ab40c64](https://user-images.githubusercontent.com/104979351/212849482-61db7db6-a19c-4d51-93a5-8a89f4ac459e.png)

![567913c892e1a513c027d5bc1c44609](https://user-images.githubusercontent.com/104979351/212849515-8c90a0f8-a5d0-400f-ab4f-33aab8d071b0.png)

🦋 **Additional context**
Add any other context about the problem here like your python setup.

**Comment by AlbinSou** [comment]
Maybe Linked to #1274. Are you using OnlineCLScenario ?

**Comment by Xuxuduoyu** [comment]
> Maybe Linked to #1274. Are you using OnlineCLScenario ?

But this is not online continuous learning. My Settings are that the current task data size is 5000, the buffer size is 2000, and mini-batch size=64.

**Comment by AntonioCarta** [comment]
- are you using Avalanche 0.3.1? If not, you should because we improved replay performance in the last release.
- are there any other processes using the GPUs that may slow you down?

If there are no external causes, this behavior is quite surprising. Epoch time should not increase, and definitely not inside the same experience.
Can you provide a minimal working example?

**Comment by Xuxuduoyu** [comment]
> * are you using Avalanche 0.3.1? If not, you should because we improved replay performance in the last release.
> * are there any other processes using the GPUs that may slow you down?
> 
> If there are no external causes, this behavior is quite surprising. Epoch time should not increase, and definitely not inside the same experience. Can you provide a minimal working example?
  First of all, thank you very much for your willingness to answer my questions
  My version is the new 0.3.1, but I trained it with a cpu.
  Now I am an undergraduate student, and I just get to know the relevant content of continuous learning, so I am not quite familiar with it.
  My training method is to add replay plugin to naive strategies. The plug-in parameter is only designed for mem_size=2000, and the rest is default. About the 16th epoch of the second experience, the time begins to increase significantly.
  The code is written as the tutorial.

**Comment by Xuxuduoyu** [comment]
> * are you using Avalanche 0.3.1? If not, you should because we improved replay performance in the last release.
> * are there any other processes using the GPUs that may slow you down?
> 
> If there are no external causes, this behavior is quite surprising. Epoch time should not increase, and definitely not inside the same experience. Can you provide a minimal working example?
Hello, I have solved this problem. I used to train with cpu. I don't have the problem of training slower and slower with the GPU.

**Comment by AntonioCarta** [comment]
Great, thanks for the update.
