### ISSUE TITLE
What are the best class-IL methods to be compared?

### ISSUE THREAD

**Issue by ChenJunzhi-buaa** [ContinualAI/avalanche#1298]
I try to write a paper about class-IL, and I need to compare the SOTA method. 

I want to know what are the best class-IL methods to be compared? Are them in avalanche? It seems that the methods in avalanche is classic but not very new.

Or how can I compare my methods with SOTA fairly? What about the setting of the hyperparameters？Are there acknowledged benchmarks and SOTAs？

Who can help me? Thank you very much！

**Comment by AntonioCarta** [comment]
Please don't open issues for general help about continual learning. You can post questions on the ContinualAI slack channel.

**Comment by ChenJunzhi-buaa** [comment]
> Please don't open issues for general help about continual learning. You can post questions on the ContinualAI slack channel.

Can you tell me where is “ContinualAI slack channel”？ Thank you！

**Comment by AntonioCarta** [comment]
https://www.continualai.org/about-us/join-us
