### ISSUE TITLE
Replace `higher` with `functorch`

### ISSUE THREAD

**Issue by HamedHemati** [ContinualAI/avalanche#1318]
[functorch](https://pytorch.org/functorch/stable/) is a good alternative for `higher` (which is not maintained anymore) in meta-learning-based strategies and, in general, any type of strategy that requires dynamic model generation or efficient computation of Hessian. Currently, LaMAML uses `higher`. I'm creating this issue to (1) remove the requirement for the installation of `higher`  (2) provide an example of how it can be used for fast updates in the inner loop of meta-learning-based strategies in Avalanche.

**Comment by AntonioCarta** [comment]
From functorch doc:
> This library is currently in [beta](https://pytorch.org/blog/pytorch-feature-classification-changes/#beta). What this means is that the features generally work (unless otherwise documented) and we (the PyTorch team) are committed to bringing this library forward. However, the APIs may change under user feedback and we don’t have full coverage over PyTorch operations.

Given the situation, I think we can keep both higher and functorch for now and remove higher only once functorch is beta (to avoid more work).

**Comment by HamedHemati** [comment]
@AntonioCarta Yea will keep the higher version for now and add the `functorch`-based one as the default strategy.

**Comment by HamedHemati** [comment]
Done.
