### ISSUE TITLE
How to work with batch size=1?

### ISSUE THREAD

**Issue by pzSuen** [ContinualAI/avalanche#1325]
Due to model limitations, I can only set the batch size to 1.
And the size of each data in my datasets is (`n`,1024), and `n` is the number of features of each input data, rather than the typical (1,1024) per data. Furthermore, `n` is different for each data.

But when using the JointTraining Scenario, my `batch_size > = len(datasets)`.
![image](https://user-images.githubusercontent.com/43957007/226418378-087e3f8b-97aa-4686-b1fa-cd970e4d0794.png)

And when using the replay plugin, it concatenates the data which is not working for my data.
![image](https://user-images.githubusercontent.com/43957007/226418519-1659c17f-db9c-49b8-a395-fa9a9a35b243.png)

**My question is, how do I change the code if I want to use the above method with batch size=1?**

Looking forward to your reply!

**Comment by AntonioCarta** [comment]
You need to change the dataloader, because by default it tries to balance the mini-batch by task. You can look how we do it for [replay](https://github.com/ContinualAI/avalanche/blob/b225d825181df0f8a941fce51a18fef4f193150e/avalanche/training/plugins/replay.py#L73) as an example.
