### ISSUE TITLE
How can I donate to ContinualAI in China?

### ISSUE THREAD

**Issue by zugexiaodui** [ContinualAI/avalanche#1328]
How can I donate to ContinualAI in China?
Thanks to the community for the contributions. However, it is not convinient for Chinese users to make donations. Are there any alternative ways of support?

**Comment by AntonioCarta** [comment]
This is a good point but I don't think this is the best place to ask for an answer. Have you tried the ContinualAI slack? All the people with the answers about the admin side of ContinualAI are there. I'm sure they will be able to help you.
