### ISSUE TITLE
Is there a way to install anaconda only through conda channels ?

### ISSUE THREAD

**Issue by AymenTlili131** [ContinualAI/avalanche#1364]
Hello Avalanche maintainer,
I'm trying to launch a script that does several experiments and trains models continually on a remote machine (I have ssh and FTP access) 
this specific machine does not support pip installing 
which is highlighted by the last command's output .

(the translation of the error is "bad interpreter:no file or directory of this type"
![image](https://user-images.githubusercontent.com/75742617/236849510-bd8e463b-d2df-49e8-a5d1-403ca6ca5eb3.png)

following the instructions in the [installation guide](https://avalanche.continualai.org/getting-started/how-to-install) to install with conda ,calling the .yml gets me through a good chunck of the installation but it also fails when it's time to install packages available only under pip .

Another Naive workaround I tried is copying the avalanche directory from a machine where it works 
/home/crns/anaconda3/lib/python3.9/site-packages/avalanche/ to the remote machine's /home/ines/anaconda3/envs/EnvFedPyt/lib/python3.7/site-packages 

I'm fully aware they have different python version but that shouldn't be an issue ,after doing so I tried to run my package.py file and to no success .
Other attempts included making my .py an exe using pyInstaller or an .sh file but that also didn't seem to work .

So is there a way to get avalanche installed on this remote machine ?

here's the file in question (in txt format) 
[package.txt](https://github.com/ContinualAI/avalanche/files/11422030/package.txt)
Thanks for the assisst

**Comment by AntonioCarta** [comment]
Hi @AymenTlili131, the problem looks like something on your side. If you have conda, you also have pip. This should work:
```
conda activate myenv
conda install pip
pip install avalanche-lib
```

If it doesn't work, you probably messed up your environments somehow (e.g. the python/pip you are using is not the one of the conda environment because of broken PATHs).
