### ISSUE TITLE
ValueError: Unsupported dataset: must have a valid targets field or has to be a Tensor Dataset with at least 2 Tensors

### ISSUE THREAD

**Issue by diakogholami7** [ContinualAI/avalanche#1378]
Im developing a simple classification project based on Avalanche using TashNet dataset. In the begining, I tried to implement a custom class that you can see below:
`
import torch as t
from torch.utils.data import Dataset

from torchvision import transforms as T
from PIL import Image
from torchvision.datasets import ImageFolder
import random
import os
from typing import Any, Tuple

class Trash(Dataset):
def init(self, root, transform=None, target_transform=None, train=True, seed=1):
self.labels = {'paper': 0, 'glass': 1, 'plastic': 2, 'cardboard': 3, 'trash': 4, 'metal': 5}
dirs = os.listdir(root)
imgs = []
for d in dirs:
path = os.path.join(root, d)
for img in os.listdir(path):
imgs.append(os.path.join(path, img))

      random.seed(seed)
      random.shuffle(imgs)
      num_train = int(0.7 * len(imgs))
      if train:
          # training
          self.imgs = imgs[:num_train]
      else:
          # validation
          self.imgs = imgs[num_train:]

      self.transform = transform
      self.target_transform = target_transform

  def __getitem__(self, index: int) -> Tuple[Any, Any]:
    
      img_path = self.imgs[index]
      target = self.labels[img_path.split('/')[-2]]
      data = Image.open(img_path)
      data = data.convert("L")
      data = self.transform(data)

      return data, torch.tensor(target)

  def __len__(self):
      return len(self.imgs)
`

As we can see, both of img and target are as a Tensor but when I run the code, it shows me this error:
ValueError: Unsupported dataset: must have a valid targets field or has to be a Tensor Dataset with at least 2 Tensors

For more info:
`
from avalanche.benchmarks.generators import nc_benchmark, ni_benchmark
from avalanche.benchmarks.utils import AvalancheDataset
from torch.utils.data import random_split
from torchvision import transforms

train_dataset = Trash('dataset-resized', transform=transforms.Compose([
transforms.Resize((32, 32)),
transforms.ToTensor()
]))
test_dataset = Trash('dataset-resized', transform=transforms.Compose([
transforms.Resize((32, 32)),
transforms.ToTensor()
]))

avalanche_train_dataset = AvalancheDataset(train_dataset)
avalanche_test_dataset = AvalancheDataset(test_dataset)

num_tasks = 6

benchmark = ni_benchmark(
train_dataset, test_dataset, n_experiences=6, shuffle=True, seed=1234,
balance_experiences=True
)
`

**Comment by diakogholami7** [comment]
Im developing a simple classification project based on Avalanche using TashNet dataset. In the begining, I tried to implement a custom class that you can see below:
`
  import torch as t
  from torch.utils.data import Dataset
  
  from torchvision import transforms as T
  from PIL import Image
  from torchvision.datasets import ImageFolder
  import random
  import os
  from typing import Any, Tuple
  
  class Trash(Dataset):
      def __init__(self, root, transform=None, target_transform=None, train=True, seed=1):
          self.labels = {'paper': 0, 'glass': 1, 'plastic': 2, 'cardboard': 3, 'trash': 4, 'metal': 5}
          dirs = os.listdir(root)
          imgs = []
          for d in dirs:
              path = os.path.join(root, d)
              for img in os.listdir(path):
                  imgs.append(os.path.join(path, img))
  
          random.seed(seed)
          random.shuffle(imgs)
          num_train = int(0.7 * len(imgs))
          if train:
              # training
              self.imgs = imgs[:num_train]
          else:
              # validation
              self.imgs = imgs[num_train:]
  
          self.transform = transform
          self.target_transform = target_transform
  
      def __getitem__(self, index: int) -> Tuple[Any, Any]:
        
          img_path = self.imgs[index]
          target = self.labels[img_path.split('/')[-2]]
          data = Image.open(img_path)
          data = data.convert("L")
          data = self.transform(data)
  
          return data, torch.tensor(target)
  
      def __len__(self):
          return len(self.imgs)
`

As we can see, both of img and target are as a Tensor but when I run the code, it shows me this error:
`ValueError: Unsupported dataset: must have a valid targets field or has to be a Tensor Dataset with at least 2 Tensors`

For more info:
`
from avalanche.benchmarks.generators import nc_benchmark, ni_benchmark
from avalanche.benchmarks.utils import AvalancheDataset
from torch.utils.data import random_split
from torchvision import transforms


train_dataset = Trash('dataset-resized', transform=transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor()
]))
test_dataset = Trash('dataset-resized', transform=transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor()
]))

avalanche_train_dataset = AvalancheDataset(train_dataset)
avalanche_test_dataset = AvalancheDataset(test_dataset)

num_tasks = 6

benchmark = ni_benchmark(
    train_dataset, test_dataset, n_experiences=6, shuffle=True, seed=1234,
    balance_experiences=True
)
`

**Comment by Bard2803** [comment]
same here when I try to adjust the CORe50 dataset.

**Comment by AntonioCarta** [comment]
this is fixed in the master branch since the new benchmarks generators don't expect targets.
