### ISSUE TITLE
GEM initialization

### ISSUE THREAD

**Issue by jannat5134** [ContinualAI/avalanche#1492]
GE = GEM(
    model=model, 
    optimizer=optimizer, 
    criterion=criterion,  # assuming 'criterion' is defined elsewhere in your code 
    patterns_per_exp=1  # Adjust this as needed based on your setup
)

this code gives me error:
 BaseSGDTemplate.__init__() missing 2 required positional arguments: 'model' and 'optimizer'

**Comment by leesunmyung** [comment]
You can modify the part of the constructors in batch_obervation.py, common_templates.py and base_sgd.py.

**Comment by AntonioCarta** [comment]
You are probably using an old environment. There was a backward-incompatible change in `typing-extension`. Installing a fresh environment should fix this.
