### ISSUE TITLE
Cannot catch last subexp (Affects Online settings with access to task boundaries)

### ISSUE THREAD

**Issue by AlbinSou** [ContinualAI/avalanche#1519]
🐛 **Describe the bug**

When using the callback after_training_exp (I also tried with other callbacks and it does not work), I never encounter the last training exp of an online CL stream. This is quite problematic since it's needed in some Online methods that can access the task boundaries (i.e ICarl or LwF).

🐜 **To Reproduce**

For instance, use that plugin and add it to the examples/online_naive.py

```
class CatchLastSubExp(SupervisedPlugin):
    def __init__(self):
        pass

    def before_training_exp(self, strategy, **kwargs):
        if strategy.experience.is_last_subexp:
            import pdb;pdb.set_trace()
            print("Last")

    def after_training_exp(self, strategy, **kwargs):
        if strategy.experience.is_last_subexp:
            import pdb;pdb.set_trace()
            print("Last")
```

🐝 **Expected behavior**

The last training experience should be properly set with the flag is_last_subexp and be caught in after_training_exp and before_training_exp (and any other callback).

**Comment by AntonioCarta** [comment]
Can you confirm that this is happening only with `drop_last=True`? I will fix it and add a test in #1511

**Comment by AlbinSou** [comment]
It seems like it's happening both when drop_last=True and when drop_last=False ... So it does not seem to be the reason

**Comment by AntonioCarta** [comment]
@AlbinSou I'm unable to reproduce this with #1511. I added some tests and counted the expected number of `is_last_subexp` attributes.

**Comment by AntonioCarta** [comment]
can you check if this is still happening on the master branch?

**Comment by AlbinSou** [comment]
It's not happening anymore after #1511 . I tried both with and without drop_last=True on the modified online_replay example.
