### ISSUE TITLE
Issue with cpu_usage metric

### ISSUE THREAD

**Issue by Srijan2-0-2-3** [ContinualAI/avalanche#1520]
Hello there, so I was evaluating cpu_usage for different methods, I found the results and plotted the graph for the same. It was unusual to notice cpu_usage to be greater than 100% as greater than 100% would be both theoretically and practically impossible. I am attaching the image for your reference so that you can give a possible explanation for the same.
![image](https://github.com/ContinualAI/avalanche/assets/127767947/d2e7ab8b-4f54-4ff4-8528-6ff2b3636543)

**Comment by AntonioCarta** [comment]
100% refers to a single core. You can go above 100% with multiple cores.

**Comment by Srijan2-0-2-3** [comment]
Is there any method to find out how many cores were used for computation?
