### ISSUE TITLE
Help to handle with miniImageNet

### ISSUE THREAD

**Issue by evertonaleixo** [ContinualAI/avalanche#1534]
Hello, it is not exactly a bug. 

I have a doubt. 
What is the simplest architecture model to handle miniImageNet?

I try a VGG16, but the size of the input in a VGG16 is 224. As miniImageNet samples have 64x64, I changed the first Linear Layer to maintain the structure.

However, I only got an accuracy of 50% in the easiest task. The other tasks get lower accuracy. I divide the dataset into 20 tasks, so, the model is predicting only few classes per task.

Thank you.

**Comment by AntonioCarta** [comment]
Hi, you can find more help on the ContinualAI slack. We use issues only for Avalanche bugs. Check the literature to find a good starting point.
