### ISSUE TITLE
support python 3.11

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#1537]
### Discussed in https://github.com/ContinualAI/avalanche/discussions/1536

<div type='discussions-op-text'>

<sup>Originally posted by **LaurenzBeck** November 24, 2023</sup>
I would really appreciate the support of python 3.11
Currently, Version resolution fails with [poetry](https://python-poetry.org/), so I am not ably to install the library with my preferred stack.
Is there a technical reason why 3.11 is not supported yet, or was there simply no time/need yet?

thx for the good work and the awsome package!</div>

**Comment by Daniel451** [comment]
Is there any update on this?

**Comment by AntonioCarta** [comment]
3.11 is supported now. We are going to release avalanche-lib 0.5.0 soon.
