### ISSUE TITLE
Code from Avalanche Tutorial doesn't work

### ISSUE THREAD

**Issue by ReemSharwalla** [ContinualAI/avalanche#1547]
Hi all,  I'm new to Avalanche. I started with the tutorial but a code in the tutorial didn't work. Can some one please help me? 
**The code:** 
from torch.optim import SGD
from torch.nn import CrossEntropyLoss
from avalanche.models import SimpleMLP
from avalanche.training.supervised import Naive, CWRStar, Replay, GDumb, Cumulative, LwF, GEM, AGEM, EWC  
model = SimpleMLP(num_classes=10)
optimizer = SGD(model.parameters(), lr=0.001, momentum=0.9)
criterion = CrossEntropyLoss()
cl_strategy = Naive(
    model, optimizer, criterion,
    train_mb_size=100, train_epochs=4, eval_mb_size=100
) 
**The error:**

TypeError                                 Traceback (most recent call last)
Cell In[65], line 9
      7 optimizer = SGD(model.parameters(), lr=0.001, momentum=0.9)
      8 criterion = CrossEntropyLoss()
----> 9 cl_strategy = Naive(
     10     model, optimizer, criterion,
     11     train_mb_size=100, train_epochs=4, eval_mb_size=100
     12 )

File ~/anaconda3/envs/sa/lib/python3.8/site-packages/avalanche/training/supervised/strategy_wrappers.py:102, in Naive.__init__(self, model, optimizer, criterion, train_mb_size, train_epochs, eval_mb_size, device, plugins, evaluator, eval_every, **base_kwargs)
     65 def __init__(
     66     self,
     67     model: Module,
   (...)
     79     **base_kwargs
     80 ):
     81     """
     82     Creates an instance of the Naive strategy.
     83 
   (...)
    100         :class:`~avalanche.training.BaseTemplate` constructor arguments.
    101     """
--> 102     super().__init__(
    103         model,
    104         optimizer,
    105         criterion,
    106         train_mb_size=train_mb_size,
    107         train_epochs=train_epochs,
    108         eval_mb_size=eval_mb_size,
    109         device=device,
    110         plugins=plugins,
    111         evaluator=evaluator,
    112         eval_every=eval_every,
    113         **base_kwargs
    114     )

File ~/anaconda3/envs/sa/lib/python3.8/site-packages/avalanche/training/templates/common_templates.py:122, in SupervisedTemplate.__init__(self, model, optimizer, criterion, train_mb_size, train_epochs, eval_mb_size, device, plugins, evaluator, eval_every, peval_mode)
     82 def __init__(
     83     self,
     84     model: Module,
   (...)
     96     peval_mode="epoch",
     97 ):
     98     """Init.
     99 
    100     :param model: PyTorch model.
   (...)
    120         `eval_every` epochs or iterations (Default='epoch').
    121     """
--> 122     super().__init__()  # type: ignore
    123     BaseSGDTemplate.__init__(
    124         self=self,
    125         model=model,
   (...)
    135         peval_mode=peval_mode,
    136     )

File ~/anaconda3/envs/sa/lib/python3.8/site-packages/avalanche/training/templates/observation_type/batch_observation.py:16, in BatchObservation.__init__(self)
     15 def __init__(self):
---> 16     super().__init__()
     17     self.optimized_param_id = None

TypeError: __init__() missing 2 required positional arguments: 'model' and 'optimizer'

I hope some can help me. I also tried to import: from avalanche.training import Naive, CWRStar, Replay, GDumb, Cumulative, LwF, GEM, AGEM, EWC  # Without .supervised but it didn't work also

**Comment by AntonioCarta** [comment]
This looks like an issue with your installation. You should try on a fresh environment. The error that you get happens when you have the wrong version of typing-extensions.
