### ISSUE TITLE
Avalanche doesn't work well in Google Colab

### ISSUE THREAD

**Issue by soorasa** [ContinualAI/avalanche#1603]
I tried to run my code in colab using this code '!pip install avalanche-lib' but I got this error:

![Bildschirmfoto 2024-02-21 um 15 25 57](https://github.com/ContinualAI/avalanche/assets/160751272/aa70aaa2-3f2b-4318-ae57-0d2a303eacf8)
There is something wrong with the typing-extensions which doesn't let me the results of the metrics.

I even tried to run a tutorial in colab but it didn't work at all:
![Bildschirmfoto 2024-02-21 um 15 30 02](https://github.com/ContinualAI/avalanche/assets/160751272/9ced74fa-c07c-4b53-bdb9-46e3bfb0bb44)

**Comment by AntonioCarta** [comment]
This should be fixed in the master branch now.
