### ISSUE TITLE
Import "avalanche" could not be resolved Pylance

### ISSUE THREAD

**Issue by pris0** [ContinualAI/avalanche#1635]
![screen](https://github.com/ContinualAI/avalanche/assets/152632307/2583d3ed-3d6e-4bbf-ae6c-5c65633fd9cd)
Hello, I have installaded avalanche (pip install avalanche-lib) in the virtual environment of my project. When I run the code from the terminal, it works without warnings (it stops because of a problem but that's another issue). In the "problems" section of vs code I get warnings for all imports regarding avalanche.
In fact, I am not able to run the debugger on my project because of this.
The venv is activated. I have already tried to re-install avalanche but I keep getting the same problem.
I though it was related to vs code not finding imports from /src/ at first, so I moved everything in the root folder but to still doesn't work...
Thank you in advance

**Comment by AntonioCarta** [comment]
Hi, unfortunately this is an issue with your environment or IDE, not with Avalanche.
