### ISSUE TITLE
Support for Latent Replay

### ISSUE THREAD

**Issue by ZexinLi0w0** [ContinualAI/avalanche#1651]
I see currently in training strategies, [AR1](https://avalanche-api.continualai.org/en/v0.5.0/generated/avalanche.training.AR1.html#avalanche.training.AR1) is implemented with latent replay, but it seems that this strategy is still in beta testing, and there still exists tight coupling among AR1, latent replay, and model=MobilenetV1 is hard coded.

Is it possible to support the latent replay method in a separate way?

🐛 **Describe the bug**

🐜 **To Reproduce**
A [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) to reproduce the issue. The code should be executable without modifications.

🐝 **Expected behavior**

🐞 **Screenshots**

🦋 **Additional context**
Add any other context about the problem here like your python setup.

**Comment by AntonioCarta** [comment]
As far as I know, each latent replay method is quite different from the others, so it may be difficult to create a general component. I think AR1 solution is quite good, so if you want to implement your own method you can easily start from that and modify it for your needs.
