### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Navya-sree-yellina** [ContinualAI/avalanche#1653]
🐛 Describe the bug
When attempting to install Avalanche version 0.3.0 using pip, the installation process fails with a FileNotFoundError originating from the setup script. The script seems to be trying to access a file (doc/overview.rst) that doesn't exist.

🐜 To Reproduce

Activate the Conda environment (myenv).
Run the command pip install avalanche.
🐝 Expected behavior
The Avalanche package should be installed successfully without any errors.

🐞 Screenshots
(myenv) navyachoudhary@Navyas-MacBook-Pro AVA % pip install avalanche 

Collecting avalanche
  Using cached avalanche-0.3.0.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qz/z2fddblj70jczfgc9910tsmw0000gn/T/pip-install-uj5to2__/avalanche_f4ae2ecec22b4923ac67f0b6f85d5a2f/setup.py", line 28, in <module>
          long_description = open('doc/overview.rst').read(),
                             ^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'doc/overview.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

🦋 Additional context

Python version: Python 3.8.19
Operating System: sanoma 14.5
Python environment setup: Conda with Python version Python 3.8.19

**Comment by AntonioCarta** [comment]
HI, the correct package is [avalanche-lib](https://pypi.org/project/avalanche-lib/)
