### ISSUE TITLE
Add (Lopez-paz, 2017) Metrics: ACC, FWT & BWT

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#212]
We should add the metrics proposed in (Lopez-paz, 2017) within the **beta version** of Avalanche.

**Comment by ryanlindeborg** [comment]
I'd love to work on this issue

**Comment by vlomonaco** [comment]
Perfect @ryanlindeborg, refer to @AndreaCossu for any problem/doubts you may encounter! :)
