### ISSUE TITLE
Remove Numpy as Avalanche core Dependency

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#252]
Where possible we should stick to torch instead of numpy in the avalanche core (i.e. we should change parts that use np at the moment instead of torch).  So that in the future we may leave numpy as an optional dependency.

**Comment by AntonioCarta** [comment]
Is this even possible? We also have other dependencies that need numpy.

**Comment by vlomonaco** [comment]
Ok closing this issue for now
