### ISSUE TITLE
iNaturalist large-scale dataset implementation

### ISSUE THREAD

**Issue by Mattdl** [ContinualAI/avalanche#298]
Porting auto-prep of the iNaturalist dataset setup from https://github.com/Mattdl/CLsurvey

**Comment by Mattdl** [comment]
Currently also preparing a classic benchmark so it's directly ready to use.

**Comment by vlomonaco** [comment]
That would be perfect, thanks!

**Comment by Mattdl** [comment]
I need to add a new dependency for parsing the JSON: https://github.com/cocodataset/cocoapi
The JSON in iNaturalist is defined following the coco API. 
https://github.com/cocodataset/cocoapi/blob/master/license.txt
It has a FreeBSD license, which means we can use the code directly given copyright notice + license file.

However, to avoid having another license file, we could just use it as an optional dependency like they do in pytorch?
See: https://pytorch.org/vision/stable/_modules/torchvision/datasets/coco.html#CocoDetection

**Comment by vlomonaco** [comment]
No problem @Mattdl you can add it for now as an avl dependency in: 

- setup.py
- environment.yml
- environment-dev.yml
- https://github.com/ContinualAI/avalanche/blob/master/docs/gitbook/getting-started/how-to-install.md
