### ISSUE TITLE
Deep API Doc Check & Update

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#318]
We should check & update the API doc for every module:

- [x] Benchmarks - @lrzpellegrini 
- [x] Training - @AntonioCarta 
- [x] Evaluation - @AndreaCossu 
- [x] Logging - @AndreaCossu 
- [x] Models - @vlomonaco 

I've noticed it is outdated in some parts.

**Comment by AndreaCossu** [comment]
I'll check the `TensorboardLogger` and then work on the docs.

**Comment by vlomonaco** [comment]
I've added a bit of doc at sub-module level in https://github.com/ContinualAI/avalanche/commit/e82f46bd11ef0ed239f87671b28ec9c2c6814485

**Comment by AndreaCossu** [comment]
I think we can close this issue and continue to update documentation as the project goes on.
