### ISSUE TITLE
Add a README for each major module

### ISSUE THREAD

**Issue by lrzpellegrini** [ContinualAI/avalanche#319]
Hello everyone, I noticed that many big projects use a module-specific README.md to better explain the features provided by each module (and to provide extended examples).

This kind of README usually contains a very high-level description of the content of that module (and its sub-modules), should have a proper list of references to the related (gitbook) tutorials and finally give some examples ranging from "newbie" to "advanced".

I think that we should add at least a README for each of the major sub-modules: benchmarks, training, logging and evaluation. Adding a short README for the "models" module may be a good idea, too.

What do you think of that?

**Comment by vlomonaco** [comment]
Moving this issue in discussions till we agree if we really need it.
