### ISSUE TITLE
pip install does not work with Python 3.8.5

### ISSUE THREAD

**Issue by ludc** [ContinualAI/avalanche#367]
Hi,

 Installation requires python<=3.8 and does not work with python 3.8.5. Is it necessary ?

**Comment by vlomonaco** [comment]
Hi @ludc! Thanks for reporting this. Actually, we noticed that with py3.9 there are some problems so we just stickled to '>=3.6,<=3.8' for simplicity. There are no strong constraints about it. We will extend support to py3.9 ASAP. 

In the meanwhile, we recommend installing the tool [via conda](https://avalanche.continualai.org/getting-started/how-to-install#install-avalanche-with-anaconda) (eventually in [developer-mode)](https://avalanche.continualai.org/getting-started/how-to-install#developer-mode-install).

Of course if you want to use py3.9 for other reasons you can tweak the install script and create a conda env with py3.9. Let us know how it works out and what's the conflicting package! :)

**Comment by vlomonaco** [comment]
Hi @ludc I looked a bit more into the issue, now you should be able to install avalanche via pip with python 3.8.5. Let me know if it works and we can close this issue!
