### ISSUE TITLE
Improving Evaluation Module Doc + Examples

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#379]
We should definitely:

- [x] Expand and Refine the Evaluation chapter on the FZTH tutorial (after @AntonioCarta integration with colab)
- [ ] Add new examples on how to use the metrics off-the-shelf
- [ ] Any other improvement

**Comment by MattiaSangermano** [comment]
I noticed that in the tutorial `How to install` in step 3 of the code in the subsections `On Windows and Mac OS`, the .yml files have been swapped between developer mode and standard mode. In fact, in the standard installation, the `environment-dev.yml` file is used while in developer mode the` environment.yml` file is used.

**Comment by vlomonaco** [comment]
Thanks @MattiaSangermano for reporting it, it should be fixed now :)

**Comment by AndreaCossu** [comment]
I'll close this issue, I opened separate issues to keep track.
