### ISSUE TITLE
Add new shiny badges :)

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#380]
It would be nice to have a few more github badges to add in our readme!

**Comment by vlomonaco** [comment]
@ggraffieti current badges are not totally self explanatory.. can we make the text labels more explicit?
like "docstring coverage" and "test coverage" or something similar? :)
Also a nice code-quality badge would be nice to have!

**Comment by AntonioCarta** [comment]
Can I close this? I think we have everything that we wanted.
