### ISSUE TITLE
Port notebooks on Colab and Sync them with Gitbook

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#381]
We need to create a deep sync with the gitbook website and colab, so that the fzth tutorial is only modified from notebooks on colab.

**Comment by AntonioCarta** [comment]
gitbook is now synced with colab. Markdown does not support the complete gitbook syntax so there are some stylistic differences. I don't think there's any way to solve this limitation if we want to keep the notebooks.

**Comment by vlomonaco** [comment]
What are the main differences? Only the final link to colab?

**Comment by AntonioCarta** [comment]
I think gitbook extends markdown with custom syntax for references or custom blocks. This is not compatible with plain notebooks (e.g. everything that uses curly braces).

**Comment by AntonioCarta** [comment]
Is there anything else to do in order to close this issue?

**Comment by vlomonaco** [comment]
On this I think we need to take a stronger decision. If we want to have the gitbook doc in sync with the notebooks we need to do it also for the examples and the 5 minutes tutorial other than the remaining chapters of the FZTH series. Otherwise we need to take a step back and maintain the doc separately from the notebooks in colab.

I'm voting for the second options as we are loosing to much gitbook functionalities. Plus, it is ok if the doc is lagging a bit behind. The actual runnable notebook should take priority. I know that this is a bit of an overhead for us, but if we remember to replicate changes as soon as we make them I think it's the best solution. Let me know what you think!

**Comment by ggraffieti** [comment]
We can Sync the notebook on ContinualAI/Colab with the notebook in avalanche used for the documentation (folder `notebooks`). 
Let me know, it wouldn't be a difficult feature.

**Comment by vlomonaco** [comment]
Yes, @ggraffieti the last step to close this issue would be to push changes to ContinualAI/Colab, you can contact @AntonioCarta if you need additional access rights to do so!

**Comment by AntonioCarta** [comment]
Let me know if there are some changes that we need to consider in ContinualAI/colab to make the process easier.

**Comment by vlomonaco** [comment]
We decided to not proceed with this.
