### ISSUE TITLE
Fix Quick Example in README

### ISSUE THREAD

**Issue by christam96** [ContinualAI/avalanche#390]
Currently the Quick Example in Avalanche's README does not run because of old import statements. This can be fixed easily by looking at the code base and updating the relevant import paths.

![image](https://user-images.githubusercontent.com/20301223/111009958-e7382600-8349-11eb-8ac7-c522a0f00733.png)

**Comment by christam96** [comment]
Happy to self-assign, but I don't think I have assignment privileges.

**Comment by vlomonaco** [comment]
Thank you so much @christam96 for the heads-up, merged in #391.
