### ISSUE TITLE
StreamForgetting MetricPlugin

### ISSUE THREAD

**Issue by Mattdl** [ContinualAI/avalanche#461]
See Discussion #460. Implementing StreamForgetting in the same vein as StreamAccuracy.

**Comment by vlomonaco** [comment]
Why is this a bug? Isn't it just an additional feature?

**Comment by Mattdl** [comment]
Yes, but it seems as a collaborator I can't assign anyone nor change the label of the issue after creating it. So if you can remove the bug-label, be my guest! (:

**Comment by Mattdl** [comment]
Also I'm trying to assign myself but I don't seem to have the permissions for it either.
