### ISSUE TITLE
Lazy scenario construction for Permuted MNIST

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#463]
I'm trying to run PMNIST using a large number of experiences. This is slow because all the permutations are built inside the constructor by copying and permuting the data repeatedly. Can we speed up this process with lazy computations by computing them only as needed? 

Maybe there is also a general need for some support for lazy generation of experiences whenever there are a large number of them.

**Comment by Mattdl** [comment]
I've experienced the same issue, also with RotatedMNIST. I think we can just use a fixed transform (permutation for PMNIST or rotation for RMNIST) which is applied by the generator when fetching the data.
