### ISSUE TITLE
Experiments are not reproducible when `fixed_class_order` is used in a scenario 

### ISSUE THREAD

**Issue by MattiaSangermano** [ContinualAI/avalanche#492]
I noticed that every time I create a scenario if I use the `fixed_class_order` option and run the experiment several times the accuracy at the end of the training are always different. This happens both if I create a scenario from scratch (using `nc_scenario`) or using an existing banchmark

**To Reproduce**
```python
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

scenario = SplitMNIST(
        n_experiences=5, return_task_id=False,
        seed=1234, fixed_class_order=[0, 9, 1, 2, 3, 4, 5, 6, 7, 8])

model = SimpleMLP(num_classes=10)
replayPlugin = ReplayPlugin(mem_size=200)

sgd = SGD(model.parameters(), lr=0.1) 
cl_strategy = Naive(
    model, sgd, CrossEntropyLoss(), train_mb_size=20,
    train_epochs=1, eval_mb_size=100, plugins=[replayPlugin],
    device=device
)

for step in scenario.train_stream:
    train_metrics = cl_strategy.train(step, num_workers=0)
    cl_strategy.eval(scenario.test_stream,num_workers=0)
```

**Expected behavior**
I expect all metrics at the end of the training to have the same value when I run the experiments multiple times, as happens when I do not use the `fixed_class_order` option.

**Comment by AndreaCossu** [comment]
Hi @MattiaSangermano ! The seed parameter only fixes the random choices when building the scenario. I suggest you to fix the random seed in the main, right after the imports, with something like ([see here](https://discuss.pytorch.org/t/how-could-i-fix-the-random-seed-absolutely/45515)):

```
torch.manual_seed(123)
torch.cuda.manual_seed(123)
np.random.seed(123)
random.seed(123)
torch.backends.cudnn.enabled=False
torch.backends.cudnn.deterministic=True
```

I am able to get the exact same results with your example if I add the aforementioned lines. Let me know if we need to dig deeper into this :smile:

**Comment by MattiaSangermano** [comment]
Ops, thank you @AndreaCossu

**Comment by vlomonaco** [comment]
@MattiaSangermano can we close this issue? :)

**Comment by MattiaSangermano** [comment]
@vlomonaco Yes, thank you!
