### ISSUE TITLE
Speed Starting Evaluation PMNIST

### ISSUE THREAD

**Issue by JonasFrey96** [ContinualAI/avalanche#494]
Hello, 

when using PMNIST starting the evaluation takes over 30-90s "sometimes". 
Is this delay related to creating the dataset ? 
The issue can be reproduced by running the AGEM example.
Updating the datasets after training only takes 10s. 
Tested on an Nvidia TITAN Xp, AMD Ryzen 7 3700X.

Best regards,
Jonas

**Comment by vlomonaco** [comment]
Hi @JonasFrey96 thanks for reporting the issue, I'll look into that and circle back to you ASAP!

**Comment by EdenBelouadah** [comment]
I think that the reason why there's a delay between training and evaluation is that the after_training_exp() function from the AGEM plugin is being executed. Try to print a message at the beginning and at the end of after_training_exp() in the file avalanche/avalanche/training/plugins/agem.py and check if it's the reason.

**Comment by JonasFrey96** [comment]
I fixed the bug in my lates PR.
Best Jonas
