### ISSUE TITLE
Examples throwing runtime error

### ISSUE THREAD

**Issue by TheRisenPhoenix** [ContinualAI/avalanche#507]
**Describe the bug**
The examples from the Readme and from /getting-started/learn-avalanche-in-5-minutes are not working and throw a runtime error:
        

> RuntimeError: 
> An attempt has been made to start a new process before the
> current process has finished its bootstrapping phase.
> This probably means that you are not using fork to start your
> child processes and you have forgotten to use the proper idiom
> in the main module:
> 
> if __name__ == '__main__':
> freeze_support()
> ...
> 
> The "freeze_support()" line can be omitted if the program
> is not going to be frozen to produce an executable.

**The stacktrace:**

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
>     prepare(preparation_data)
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
>     main_content = runpy.run_path(main_path,
>   File "[python-dir]\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "[python-dir]\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "[python-dir]\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "[project-dir]\Test.py", line 31, in <module>
>     cl_strategy.train(train_task, num_workers=4)
>   File "[project-dir]\venv\lib\site-packages\avalanche\training\strategies\base_strategy.py", line 249, in train
>     self.train_exp(exp, eval_streams, **kwargs)
>   File "[project-dir]\venv\lib\site-packages\avalanche\training\strategies\base_strategy.py", line 279, in train_exp
>     self.training_epoch(**kwargs)
>   File "[project-dir]\venv\lib\site-packages\avalanche\training\strategies\base_strategy.py", line 417, in training_epoch
>     for self.mb_it, self.mbatch in \
>   File "[project-dir]\venv\lib\site-packages\avalanche\benchmarks\utils\data_loader.py", line 109, in __iter__
>     iter_dataloaders[tid] = iter(dl)
>   File "[project-dir]\venv\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
>     return self._get_iterator()
>   File "[project-dir]\venv\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
>     return _MultiProcessingDataLoaderIter(self)
>   File "[project-dir]\venv\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
>     w.start()
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
>     return Popen(process_obj)
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
>     _check_not_importing_main()
>   File "[python-dir]\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
>     raise RuntimeError('''

**To Reproduce**
- Install avalanche along with all missing dependencies via pip as described in the tutorial.
- Create a new python file, paste the code from the readme or the /getting-started/learn-avalanche-in-5-minutes into it and execute
- A runtime error is thrown

**Expected behavior**
The examples should work

**Additional context**
I experienced it in my actual python project, but also tried it in a clean and empty project. All missing dependencies (tqdm and googledrivedownloader) are installed. Python version is 3.8.9.

**Comment by AntonioCarta** [comment]
Are you on Windows? try setting `num_workers=0`. On my Windows machine, dataloaders with multiprocessing give the same error. We need to remove the `num_workers` argument on the notebooks to fix this error on Windows.

**Comment by TheRisenPhoenix** [comment]
Thank you!
That indeed solved the issue.
