### ISSUE TITLE
Expand input parameters to the W&BLogger class

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/avalanche#511]
Currently, WandBLogger accepts a `init_kwargs` as input parameter. I think we should avoid a dictionary if possible and prefer explicit parameters passed to the constructor. Most of them should be made optional. This can be implemented directly in #483 .
For example, by default the `project` and `run` parameters could be set to `avalanche` and `test`, respectively.

**Comment by digantamisra98** [comment]
We can do that yes but might limit the flexibility of different parameter usage. For example, `entity` is a common init parameter used to define the account you want it to log on if you have multiple teams account. Maybe we can keep some as default and have rest to be defined in a dict separately?

**Comment by digantamisra98** [comment]
Fixed. This issue can be closed now.
