### ISSUE TITLE
W&B Artifacts support

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/avalanche#512]
We should integrate W&B Artifacts in the W&B Logger we currently have.

**Comment by digantamisra98** [comment]
Sure, will start on it this week

**Comment by digantamisra98** [comment]
@AndreaCossu Here is a basic implementation of artifacts on my [fork](https://github.com/digantamisra98/avalanche/blob/7c54e12a9507c3831d8e7034bc8e5917456115ab/avalanche/logging/wandb_logger.py#L109)

**Comment by AndreaCossu** [comment]
I think this is closed by #672 , right @digantamisra98 ?

**Comment by digantamisra98** [comment]
Yes
