### ISSUE TITLE
Add Doc + Utils to Support Multiple Streams for Benchmark

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#519]
PR #516 added support for additional custom streams in the scenario object. We should add a bit more support to the generators for this case as well as updating the documentation accordingly.

**Comment by lrzpellegrini** [comment]
Hi there, I'm in the process of implementing the support for custom streams in the higher-level API. The main problem is that current methods are difficult to adapt without introducing breaking changes, which in turn may disrupt existing codebases.

Considering the fact that we also need to tackle #503, I was thinking about creating a parallel set of sub-modules by deprecating the existing ones.

This would require creating a new version of the following scripts:
- avalanche.benchmarks.scenarios.generic_scenario_creation (which currently contains the mid-level API)
- avalanche.benchmarks.generators.scenario_generators (which currently contains the higher-level API)

Inside of the new scripts we can then implement the updated nomenclature + custom stream support. Does this make sense to you?

**Comment by vlomonaco** [comment]
Ok, it works for me!

**Comment by lrzpellegrini** [comment]
The last thing we have to decide is the nomenclature (issue #503). If we want to make it explicit that new helpers are different than the deprecated ones we have decide a new name for both the scripts and the helper methods. In fact, there is no need to change the name of the script if we don't want to, but we still need a new name for each helper. Do you have any good suggestion? 

We need to rename those things:
- Script `generic_scenario_creation.py` contains:
  - `create_multi_dataset_generic_scenario`
  - `create_generic_scenario_from_filelists`
  - `create_generic_scenario_from_paths`
  - `create_generic_scenario_from_tensor_lists`
- Script `scenario_generators.py` contains:
  - `nc_scenario`
  - `ni_scenario`
  - `dataset_scenario`
  - `filelist_scenario`
  - `paths_scenario`
  - `tensors_scenario`

**Comment by vlomonaco** [comment]
I'd just change the world "scenario" with "benchmark". What do you think?

**Comment by lrzpellegrini** [comment]
Makes sense. This would also involve the name of the scripts, right?

**Comment by vlomonaco** [comment]
Only documentation missing for this.
