### ISSUE TITLE
ContinualAI-bot could comment a PR if there are problems with PEP8

### ISSUE THREAD

**Issue by ggraffieti** [ContinualAI/avalanche#531]
Now, if there are problems with pep8 in a PR, the tests correctly find them. However, the user has to open the low-level action console to find out where the problems are (file, line). 
It would be more convenient if the issues are reported as a comment in the PR, so the user doesn't have to go through the action console. 
A comment may be something like: 

_Oh no :(  Seen that there are some PEP8 errors. 
Here's a report of where you can find them them :)  
avalanche/evaluation/metrics/forward_transfer.py:47:81: E501 line too long (86 > 80 characters)
avalanche/evaluation/metrics/forward_transfer.py:73:81: E501 line too long (84 > 80 characters)
avalanche/evaluation/metrics/forward_transfer.py:92:9: E265 block comment should start with '# '
avalanche/evaluation/metrics/forward_transfer.py:97:1: E302 expected 2 blank lines, found 1_

**Comment by vlomonaco** [comment]
That would be great!!!

**Comment by ggraffieti** [comment]
Solved by #544
