### ISSUE TITLE
Update/Remove Current Auto-Download Features from Google Drive

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#533]
Currently we have `googledrivedownloader` but we don't use it since downloads from Drive are usually corrupted or interrupted for big files. We should remove it if we don't use it anymore.

In this repo they use another method to download gdrive files: https://github.com/salmank255/IJCAI-2021-Continual-Activity-Recognition-Challenge/blob/main/Data/download_data.sh

We should check if this is something we can integrate into AVL.

**Comment by digantamisra98** [comment]
Maybe use [gdown](https://pypi.org/project/gdown/)
