### ISSUE TITLE
possible bug in global_it_counter?

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#550]
I find that I have some repeated `x_values` in my metrics:
```
   "Loss_Epoch/train_phase/train_stream/Task000": [[138,138,138,138,138,138,138,138,138,138,276,276,276,276,276,276,276,276,276,276,414,414,414,414,414,414,414,414,414,414,552,552,552,552,552,552,552,552,552,552,690,690,690,690,690,690,690,690,690,690,828,828,828,828,828,828,828,828,828,828,966,966,966,966,966,966,966,966,966,966,1104,1104,1104,1104,1104,1104,1104,1104,1104,1104,1242,1242,1242,1242,1242,1242,1242,1242,1242,1242,1380,1380,1380,1380,1380,1380,1380,1380,1380,1380],[0.09099428,0.09087896,0.09076334,0.09064682,0.09052878,0.09040853,0.09028531,0.09015824,0.09002626,0.08988814,0.08974233,0.08958696,0.08941965,0.08923741,0.08903637,0.08881165,0.08855686,0.08826392,0.08792255,0.08752012,0.08704191,0.08647225,0.08579712,0.08500839,0.08410828,0.08311212,0.08204724,0.08094683,0.07984366,0.07876532,0.07773249,0.07675893,0.0758528,0.07501684,0.07425166,0.07355635,0.07292811,0.07236298,0.07185711,0.07140603,0.07100509,0.07064946,0.07033526,0.07005842,0.06981486,0.06960127,0.06941388,0.06924961,0.0691061,0.06898082,0.0688714,0.06877615,0.06869331,0.06862115,0.06855828,0.06850349,0.06845603,0.06841461,0.06837849,0.06834728,0.06832004,0.06829642,0.06827584,0.06825803,0.0682426,0.06822921,0.06821757,0.06820741,0.06819842,0.06819078,0.06818417,0.06817829,0.06817327,0.06816881,0.06816499,0.06816165,0.06815873,0.06815618,0.06815402,0.06815216,0.06815031,0.06814885,0.06814756,0.0681464,0.06814542,0.06814462,0.06814388,0.06814322,0.0681426,0.06814211,0.06814157,0.06814123,0.06814093,0.06814055,0.0681403,0.06814008,0.06813995,0.0681397,0.06813954,0.06813937]]
```
The dictionary is retrieved by `strategy.evaluator.get_all_metrics()` after training on the entire stream.
I don't know why but I don't think this should be happening.

Also, a bit unrelated but it seems that `global_it_counter` is updated during evaluation inside `after_eval_iteration`, which seems wrong, or maybe I don't understand what the `global_it_counter` is actually counting.

**Comment by AndreaCossu** [comment]
I'll take a look at it, thanks for reporting!

The global counter counts how many iterations (both training and eval iterations) there have been since the creation of the strategy. Why does it seem wrong to you?

**Comment by AntonioCarta** [comment]
> The global counter counts how many iterations (both training and eval iterations) there have been since the creation of the strategy. Why does it seem wrong to you?

I expected a counter that is updated only when the model is updated (during training). Basically, the counter is like an identifier for the model through time. During evaluation the model doesn't change, so I expected the counter to stay constant.

However, not updating during evaluation results in duplicated x_values for minibatch-level metrics. I guess both solutions make sense.

**Comment by AndreaCossu** [comment]
Yes, I chose to update it also during eval exactly to avoid the problem you are mentioning. It is not a problem now but in this way we can allow future metrics which emit values after each eval iteration.

**Comment by AndreaCossu** [comment]
Let me know if the last PR solves the bug :) It did on my side.
