### ISSUE TITLE
How-To Tutorials on Gitbook

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#568]
Avalanche is growing fast and steady in terms of new functionalities we integrate every week. We are now reaching a crucial point where it is difficult to add everything into the FZTH tutorial without making it too overwhelming. 

So the idea is to start a new section in the official avalanche website with "how-to" tutorials (runnable notebooks) addressing specific and recurrent informative needs. We could start for example from:

- [ ] Usage of AvalancheDataset advanced functionalities
- [ ] Usage of Data Loaders
- [ ] Streams slicing (horizontally, vertically)
- [ ] Replay methods (plugins, data loaders, Storage policies, implemented algorithms...)
- [ ] ...

Please write here what we should add as an additional How-to tutorial.

**Comment by ggraffieti** [comment]
I'd suggest also an expanded "How to contribute" section. 
There are some small technicalities that are currently not reported but IMO can be useful for new contributors.

**Comment by vlomonaco** [comment]
Can you make a few examples about these aspects that we are currently missing [here](https://avalanche.continualai.org/from-zero-to-hero-tutorial/09_contribute-to-avalanche)?

**Comment by AntonioCarta** [comment]
I think we should explore how other successful projects do it. For example, [pytorch](https://github.com/pytorch/tutorials) keeps separate repositories for tutorials and examples, which are automatically pushed in the website.

**Comment by ggraffieti** [comment]
> Can you make a few examples about the aspects that we are currently missing [here](https://avalanche.continualai.org/from-zero-to-hero-tutorial/09_contribute-to-avalanche)?

My points are mainly technicalities and not so important. As an example, the fact that the files and the method for unit test must start with `test`, the fact that the datasets must be always downloaded into `~/.avalanche/data` etc..
I'd suggest to add a section named `further details` in the page you mentioned to include all this little details.
