### ISSUE TITLE
Expand FZTH "models" chapter

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#571]
Expand FZTH "models" chapter to include recent PRs #535 and #430.

**Comment by AntonioCarta** [comment]
If you do it you can close also #538

**Comment by vlomonaco** [comment]
Ok I'll do it, I'll ask for your review though :)

**Comment by vlomonaco** [comment]
I think we can close this. The FZTH chapter is now in line with the features offered.
