### ISSUE TITLE
Replay not working anymore?

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/avalanche#574]
I encountered a strange behavior with `Replay` strategy. I had some experiments reaching like 80% accuracy on average on all experiences. I run again the experiments after updating avalanche and now I obtain sensibly worse performances (like 30%).

I reverted back avalanche to this commit: 9b5739dac962b9a98686deb501f4b0e7bedc9166 (before the large Replay update) and the results are back to normal.

I think we should investigate into this. If someone has already experiments with previous versions of Avalanche + replay, it would be useful to rerun them and see if it is indeed a problem of the newer version.

**Comment by vlomonaco** [comment]
Can you provide a minimal script which is able to reproduce the issue?

**Comment by AndreaCossu** [comment]
You can try with `examples/replay.py`. 
With current avalanche version I obtain `68.68%` accuracy on Experience 0 and  `38.14%` accuracy on Experience 1 after training on all 5 experiences. The other 3 experiences obtain >90%.

With old avalanche version which uses same Replay memory size I obtain (much slower execution) on Experience 0 `93.17%` and on Experience 1 `89.58%`. The other 3 experiences obtain >90%.

**Comment by lrzpellegrini** [comment]
I confirm I obtain `0.3569` accuracy on exp 1. I think that the exemplars selection mechanism have been changed recently...

**Comment by AntonioCarta** [comment]
It seems that the new `ExperienceBalancedStoragePolicy` is not balancing between experiences. I will fix this ASAP.

**Comment by lrzpellegrini** [comment]
In the meantime `ClassBalancedStoragePolicy` doesn't seem to have a call to `super`. This doesn't seem to create issues, but calling the super __init__ method is always a good idea.

Another thing: are those storage policies covered by unit tests?
