### ISSUE TITLE
AvalancheSubset 

### ISSUE THREAD

**Issue by andrew-r96** [ContinualAI/avalanche#581]
When an AvalancheSubset is returned from a benchmark the field `transform_groups` is not initialized with the original `AvalancheDataset` transform group.
```
transform = transforms.Compose([
    transforms.ToTensor(),
])

train_set = CIFAR100(expanduser("~") + "/.avalanche/data/cifar100/", train=True, download=True,)

train_set = AvalancheDataset(train_set,
                             transform_groups=dict(train=(transform, None),
                                                   eval=(transform, None)),
                             initial_transform_group='train')

scenario = nc_benchmark(
    train_dataset=train_set,
    test_dataset=train_set,
    n_experiences=10,
    task_labels=False,
    shuffle=False)

print(train_set.transform_groups)
print(scenario.train_stream[0].dataset.transform_groups)
```
Result:
```
{'train': (None, None), 'eval': (None, None)}
```
Yet, `AvalancheSubset` performs the correct transformations on the data before returning it.

**Comment by lrzpellegrini** [comment]
Hi Andrew, as of now this behavior is correct: the `AvalancheSubset` (`scenario.train_stream[0].dataset`) acts as a wrapper around the original dataset (`train_set`). This means that transformations are applied by the original dataset, but not by the `AvalancheSubset`.

**Comment by andrew-r96** [comment]
Ok got it, thank you!
So, if I need to get the original transformations I have to go through `subset._original_dataset`, right?

**Comment by lrzpellegrini** [comment]
Yes, using `subset._original_dataset` may be a way to get the original transformations. However, consider that `_original_dataset` is a protected field and the internal implementation of `AvalancheSubset` may change in the future.
