### ISSUE TITLE
Regarding CORe50 dataset

### ISSUE THREAD

**Issue by shivmgg** [ContinualAI/avalanche#624]
Hi, 

Thanks for the awesome library. May I know how to run experiments at category-level (10 classes) using the CORe50 dataset?

**Comment by vlomonaco** [comment]
Hi @shivmgg! we are planning to support it soon in #547. For now you can simply do: `cat_label = obj_label % 5`. However if you are using the classic CORe50 scenarios in NC the label map is different. You can read more about this here: https://vlomonaco.github.io/core50/#confs

**Comment by shivmgg** [comment]
Hi @vlomonaco, thanks for the quick response. The label map is different only in NC scenario, right? I can still use this logic for all the other scenarios: NI, NIC, NICv2. Is that correct?

**Comment by vlomonaco** [comment]
That's correct, only for NC is different!
