### ISSUE TITLE
Data incremental setup extremely slow

### ISSUE THREAD

**Issue by Mattdl** [ContinualAI/avalanche#650]
After the fix in #616, the data incremental setup takes an extremely long processing time.
Split-MNIST takes about 6 hours to complete, whereas usually it only takes about 10min (about factor 40 slowdown).

I don't have a log of the run available, but it should be reproducible with PR #623.

Also, I can't reproduce the CoPE results (65% w.r.t. 94% in the class-incremental setup). 
It could be I need to make some changes in the method to adapt to the data incremental setting, but I mention it because it could also have root for a bug in the data incremental benchmark generator.

**Comment by lrzpellegrini** [comment]
Hi Matt, I tried disabling the cope plugin, replacing the ppp_loss with a CrossEntropyLoss, and setting num_workers=1 and everything runs quite fast. The data incremental generator doesn't seem to be the issue here.

**Comment by Mattdl** [comment]
Yes you're right! I tried it also with the ReplayPlugin with the ClassBalancedStoragePolicy, and this gives a similar slowdown as CoPE, so probably this is the culprit.

**Comment by vlomonaco** [comment]
Ok @Mattdl so is the "ClassBalancedStoragePolicy" the problem? can you open another issue with a minimal example to reproduce the issue? thanks! :)

**Comment by AntonioCarta** [comment]
@Mattdl do you have a script to reproduce your results without Avalanche? I'm profiling the code and it seems to me that the backpropagation and moving mini-batches to the GPU are already taking more time than your 10min estimate.

How do you manage the buffer? is it stored on the GPU or do you load the images from the disk each time?

**Comment by Mattdl** [comment]
Here you can find the original codebase: https://github.com/Mattdl/ContinualPrototypeEvolution
Buffer samples are kept in GPU to speed up the process.

**Comment by AntonioCarta** [comment]
I see that you use `n_iter = 1`. However, the current avalanche implementation iterates the entire buffer at each step (200 iters with a 2000 buffer).
Can you confirm this problem? It would explain the large difference.

**Comment by Mattdl** [comment]
@AntonioCarta that's a good catch! Yes it should only do a single sampling operation on the buffer per experience (batch).
This worked for the class incremental setting, but here we need a way to only have a single sampling operation on the memory.
Is there a straightforward way to do this?

We could take a subset of the memory which we pass to the Avalanche adapted dataset, but then we do the sampling already up front. If we can give a max number of iterations on the Adapted dataset (i.e. 1 iteration) this might work?

**Comment by AntonioCarta** [comment]
I slightly prefer to leave the dataset unchanged if possible.

I see two possibilities:
- add a parameter to the DataLoader which determines whether the replay and original data should be iterated as many times as the longest/shortest among them. Right now the number of iterations equals the longest between the two.
- fix a maximum number of iterations and use `stop_training` for early stopping.

**Comment by Mattdl** [comment]
I agree that the dataset should remain unchanged. However, implementing a 'stop_training' would require me to to overwrite the `train_epoch` of the `BaseStrategy`. Right now I can work just with  the plugin, so it would be nice if I could keep it that way.

Another way would be to pass a `max_number of iterations` to the `ReplayDataloader`?

**Comment by AntonioCarta** [comment]
> I agree that the dataset should remain unchanged. However, implementing a 'stop_training' would require me to to overwrite the train_epoch of the BaseStrategy. Right now I can work just with the plugin, so it would be nice if I could keep it that way.

You can use `stop_training`, it's a `BaseStrategy` method already implemented. We use it for early stopping.

> Another way would be to pass a max_number of iterations to the ReplayDataloader?

Yes, we can also have a completely different dataloader for data-incremental settings if you think it's necessary.

**Comment by AntonioCarta** [comment]
@Mattdl any update on this? Did it solve the performance issue?

**Comment by Mattdl** [comment]
Hi @AntonioCarta, thanks for the reminder (I'm just back from my holidays)!  I'll follow it up soon (:

**Comment by Mattdl** [comment]
@AntonioCarta a question about the ReplayDataLoader: Can I enforce the ratio of sampling from the data vs the memory? e.g. with batch size 20, can I enforce 10 samples to come from the `data` and 10 from the `memory`?

**Comment by AntonioCarta** [comment]
For the moment the ratio is equal. If you set `batch_size=10` you get a batch of 20 samples, 10 from the current experience and 10 from the memory. We can add a parameter to adjust the ratio if needed.

> Edit: This was not possible so far, so I've adapted the ReplayDataLoader with a force_data_batch_size attribute so we can fix the nb of new data in each batch.

We can merge this change if you want.

Also, maybe the way the dataloader's arguments are used is counter-intuitive right now, because if you set `batch_size=10` you get 20 samples (10 from each dataloader).

**Comment by Mattdl** [comment]
Oh ok I see, thanks! 

> Also, maybe the way the dataloader's arguments are used is counter-intuitive right now, because if you set `batch_size=10` you get 20 samples (10 from each dataloader).

I'm not sure about that, because for me the `batch_size` gives the total batch size?

**Comment by AntonioCarta** [comment]
yes, you are right, I was thinking about the other data loaders, e.g. `GroupBalancedDataLoader`.

**Comment by Mattdl** [comment]
Ok I've been able to produce nearly the results for SplitMNIST, so we can merge (: Thanks for the help @AntonioCarta !

**Comment by AntonioCarta** [comment]
This is a great news!
