### ISSUE TITLE
Error in create_multi_dataset_generic_benchmark

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/avalanche#655]
Here is my example:
```
trs = [TensorDataset(torch.randn(10, 3), torch.randint(0, 3, (10,))) for i in range(3)]
tss = [TensorDataset(torch.randn(10, 3), torch.randint(0, 3, (10,))) for i in range(3)]
benchmark = create_multi_dataset_generic_benchmark(train_datasets=trs, test_datasets=tss)
benchmark.train_stream[0].classes_in_this_experience
```
output: `[tensor(2), tensor(2), tensor(1), tensor(0), tensor(1), tensor(0), tensor(0), tensor(0), tensor(2), tensor(2)]`
expected: `[0, 1, 2]`

**Comment by AndreaCossu** [comment]
This may be related to #654 since the benchmark creator internally uses `AvalancheDataset`.

**Comment by lrzpellegrini** [comment]
This seems to be related to the fact that targets are tensors instead of ints.

Tensors don't work well with Python sets and `pytorch_tensor[3]` returns a tensor with a single element (not an int or float).

This works:

```python
trs = [AvalancheTensorDataset(torch.randn(10, 3), torch.randint(0, 3, (10,)),
                              dataset_type=AvalancheDatasetType.CLASSIFICATION) for i in range(3)]
tss = [AvalancheTensorDataset(torch.randn(10, 3), torch.randint(0, 3, (10,)),
                              dataset_type=AvalancheDatasetType.CLASSIFICATION) for i in range(3)]
benchmark = create_multi_dataset_generic_benchmark(train_datasets=trs, test_datasets=tss)
```

because `dataset_type=AvalancheDatasetType.CLASSIFICATION` will convert targets to ints.

**Comment by vlomonaco** [comment]
@lrzpellegrini can we make the conversion implicit instead of forcing the user specify the dataset type? As they may also be related to non classification tasks.

**Comment by AndreaCossu** [comment]
Thanks @lrzpellegrini I'll try this out asap!

**Comment by AndreaCossu** [comment]
The `dataset_type` solved the problem. I think we should better document this into the API doc so that the user can figure this out on his own. Anyway, I'll close the issue since the specific question has been answered.
