### ISSUE TITLE
Benchmark with a task label per pattern fails on strategy.train() call

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/avalanche#657]
I am trying to train a `Naive` strategy on a fake benchmark where task labels are provided for each pattern. It seems that there is a call to `task_label` instead of `task_labels` which cause the code to fail (since `task_label` is not defined for this kind of benchmark). The error is raised on a `isinstance` check which makes it kind of hard to debug.

This is the code and the traceback:
```python
tr_ds = [AvalancheTensorDataset(torch.randn(10, 7, 3), torch.randint(0, 3, (10,)),
                                dataset_type=AvalancheDatasetType.CLASSIFICATION,
                                task_labels=torch.randint(0, 5, (10,)).tolist()) for i in range(3)]
ts_ds = [AvalancheTensorDataset(torch.randn(10, 7, 3), torch.randint(0, 3, (10,)),
                                dataset_type=AvalancheDatasetType.CLASSIFICATION,
                                task_labels=torch.randint(0, 5, (10,)).tolist()) for i in range(3)]
scenario = create_multi_dataset_generic_benchmark(train_datasets=tr_ds, test_datasets=ts_ds)
model = SimpleMLP(input_size=3, num_classes=2)
cl_strategy = Naive(model, SGD(model.parameters(), lr=0.001, momentum=0.9),
        CrossEntropyLoss(), train_mb_size=500, train_epochs=1, eval_mb_size=100,
        device='cpu', evaluator=None)
for i, experience in enumerate(scenario.train_stream):
    cl_strategy.train(experience)

Traceback (most recent call last):
  File "test.py", line 163, in <module>
    main(args)
  File "test.py", line 137, in main
    res = cl_strategy.train(experience)
  File "/home/acossu/avalanche/avalanche/training/strategies/base_strategy.py", line 221, in train
    if isinstance(experiences, Experience):
  File "/home/acossu/miniconda3/envs/avalanche-dev-env/lib/python3.8/typing.py", line 1017, in __instancecheck__
    if all(hasattr(instance, attr) and
  File "/home/acossu/miniconda3/envs/avalanche-dev-env/lib/python3.8/typing.py", line 1017, in <genexpr>
    if all(hasattr(instance, attr) and
  File "/home/acossu/avalanche/avalanche/benchmarks/scenarios/generic_cl_scenario.py", line 607, in task_label
    raise ValueError('The task_label property can only be accessed '
ValueError: The task_label property can only be accessed when the experience contains a single task label
```

**Comment by AndreaCossu** [comment]
The problem pertains to `GenericExperience` not having `task_label` property. If I add that property which always return `None` the error disappears. Of course, I don't think this is the appropriate solution since we are introducing something not needed. Maybe we need to discuss more about task label management in general in the experiences.

**Comment by AntonioCarta** [comment]
It's a type error. `train` assumes to receive an `Experience`, but your class is a `GenericExperience`, which is missing the `task_label` attribute. I'm not sure what's the difference between the two classes.

**Comment by AntonioCarta** [comment]
FYI I don't think `task_label` is needed by any strategy. Metrics may use it more extensively.

**Comment by lrzpellegrini** [comment]
I reproduced the error, and it seems to be related to the fact that `isinstance` is checking if the experience is an instance of `Experience` (should return True). The problem is that, when executing its checks, `isinstance` accesses the `task_label` field (it doesn't just check if it exists, it actually tries to gets its value) for reasons beyond my comprehension.

That field will raise and error if accessed when more than one task label is available in the dataset backing the experience (this is an expected behaviour).

For the moment, a solution is to invert [the if statement](https://github.com/ContinualAI/avalanche/blob/c659917790c4afef11555324a44b40e3b1bff241/avalanche/training/strategies/base_strategy.py#L221) as follows:

```python
if not isinstance(experiences, Sequence):
    experiences = [experiences]
```
