### ISSUE TITLE
`eval_streams` parameter of `train_exp` can't be null.

### ISSUE THREAD

**Issue by TomVeniat** [ContinualAI/avalanche#667]
🐛 **Describe the bug**
When directly using `train_exp` on a Strategy with `eval_every` >= 0 and `train_streams` set to null, the eval_stream is not set to the given experience as described in the doc, causing an error in `_periodic_eval`.

🐜 **To Reproduce**
```python
from avalanche.benchmarks.classic import SplitMNIST
from avalanche.models import SimpleMLP
from avalanche.training.strategies import Naive

from torch.optim import SGD
from torch.nn import CrossEntropyLoss

scenario = SplitMNIST(n_experiences=5)
model = SimpleMLP(num_classes=scenario.n_classes)
cl_strategy = Naive(
    model, SGD(model.parameters(), lr=0.001, momentum=0.9),
    CrossEntropyLoss(), train_mb_size=500, eval_mb_size=100, train_epochs=1,
    eval_every=0)

results = []
for experience in scenario.train_stream:

    # This line works
    cl_strategy.train_exp(experience, eval_streams=[scenario.train_stream])

    # This line breaks
    cl_strategy.train_exp(experience, eval_streams=None)
```

🐝 **Expected behavior**
I think the most intuitive behavior would be to create an evaluation stream only composed of the given training experience.

**Comment by AntonioCarta** [comment]
I agree, I'll fix it.

**Comment by AntonioCarta** [comment]
FYI if you use `train` instead of `train_exp` everything works as you expect.
