### ISSUE TITLE
Support for endless streams

### ISSUE THREAD

**Issue by lrzpellegrini** [ContinualAI/avalanche#680]
Avalanche is finally able to deal with lazily created streams (see #671). However, there are certain manipulations of lazy streams that are not compatible with some internal assumptions, mainly the assumption on the fixed size of streams.

The good part is that, while the ability to retrieve the length of a stream (for instance, via `len(benchmark_instance.train_stream)`) is a good user-facing feature, most of the other parts of Avalanche don't actively use it (strategy, metrics, loggers, ...).

On the contrary, certain manipulations, like the one required from #673, require the ability to support unbounded lazily generated streams.

The support for unbounded streams will finally allow us to consolidate the support for lazily created streams (#600).

**Comment by AntonioCarta** [comment]
Fixed by #977.
