### ISSUE TITLE
Dataset download speed is inconsistent during tests

### ISSUE THREAD

**Issue by ggraffieti** [ContinualAI/avalanche#699]
During unit test sometimes the dataset are downloaded in few seconds, while other times it takes few minutes to download them (extending the time taken to unit test). 
I noticed that the downloads using the amazon S3 mirror are usually much faster than the ones that use the original sites. 

Check if the mirror order can be changed, using the amazon mirror as first choice.

**Comment by lrzpellegrini** [comment]
We greatly reduced the dependence on external datasets in unit tests. We still download MNIST, but it seems that the download speed is now reasonable.

I'm closing this issue.
