### ISSUE TITLE
Confusion matrix with Joint Training has all zeros for last class

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/avalanche#703]
This bug was brought up [in this discussion](https://github.com/ContinualAI/avalanche/discussions/694). 
Instead of reporting confusion matrix values for all 10 classes, the result shows zeros in the last matrix column.

**Comment by amalapuram** [comment]
Hi @AndreaCossu 

Do the fix available for this bug? I have a [regression bug](https://github.com/ContinualAI/avalanche/discussions/705) associated with this

**Comment by AndreaCossu** [comment]
@amalapuram sorry, not yet but I am working on it!

**Comment by AndreaCossu** [comment]
@amalapuram can you please check if the last PR #714 solves your issue?

**Comment by amalapuram** [comment]
@AndreaCossu , thanks for the reminder.

I had one question, to validate my issue against your fix. Do I need to update my current avalanche env ? or go for fresh avalanche env setup ?

**Comment by AndreaCossu** [comment]
no, you don't have to update your env, just the code. 
If you forked/cloned the repo, you can pull changes from git, while if you installed it with pip you can rerun `pip install git+https://github.com/ContinualAI/avalanche.git`

**Comment by amalapuram** [comment]
Thanks @AndreaCossu 

I will trigger the execution, and let you know the status soon

**Comment by amalapuram** [comment]
Thanks @AndreaCossu 
you Fix is working, I resumed my work
