### ISSUE TITLE
Nightly Docker release is scheduled for pull requests

### ISSUE THREAD

**Issue by ggraffieti** [ContinualAI/avalanche#708]
The release of the nightly Docker image must be triggered only by commits to the main branch, not by pull requests. 
Problem -> release action triggered by the completion of unit test -> unit test executed in PR -> docker release triggered

No elegant way to pass information to the release action about the event that triggered the unit test. 

Most elegant solution (still not elegant in an absolute way) -> include the docker release in the unit test workflow, in order to have access to the event that triggered the tests. 

Another solution, a real nightly build -> release avalanche every night (maybe we could check the date of the last commit?) 
Problem with this solution: we don't have an updated version of avalanche every time we push something to master.

**Comment by vlomonaco** [comment]
Couldn't we use these "if" clauses for the actions? https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions

**Comment by AntonioCarta** [comment]
> Another solution, a real nightly build -> release avalanche every night (maybe we could check the date of the last commit?)

Maybe this is the easiest solution? I guess if people want a package they can wait for a day or install it by themselves.

**Comment by ggraffieti** [comment]
> Couldn't we use these "if" clauses for the actions? https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions

Since the action is triggered by the end of another action (and not from a specific repo event) the docker build is always sheduled to the master branch (i checked). 



> > Another solution, a real nightly build -> release avalanche every night (maybe we could check the date of the last commit?)
> 
> Maybe this is the easiest solution? I guess if people want a package they can wait for a day or install it by themselves.

It's also my preferred solution, probably we could retrieve the last commit data and produce the Docker image only if the last commit on master was pushed < 24h before.

**Comment by ggraffieti** [comment]
Solved with PR #709.
Now the build is scheduled every night (at midnight) and skipped if the last commit is older than 24h (no changes from the last nightly build).
