### ISSUE TITLE
Add "Accuracy for classes seen so far" metric

### ISSUE THREAD

**Issue by tachyonicClock** [ContinualAI/avalanche#712]
It is common to want to make a graph like this:
![image](https://user-images.githubusercontent.com/37557393/127932961-24bc35e5-6f40-472e-a523-77762424782c.png)
However avalanche lacks a built in metric to produce this sort of graph.

**Comment by tachyonicClock** [comment]
I'm happy to be assigned to this issue and have already started work on an implementation

**Comment by AndreaCossu** [comment]
Thanks @tachyonicClock , feel free to try it out!

**Comment by vlomonaco** [comment]
Thanks @tachyonicClock this would be great!
