### ISSUE TITLE
Any recommended ways to combine Torchvision pretrained models and MultiTaskModule?

### ISSUE THREAD

**Issue by dsoselia** [ContinualAI/avalanche#715]
Seems somewhat hard since MultiTaskModule expects task id argument.

**Comment by AndreaCossu** [comment]
Hi @dsoselia ! What do you mean with combining? Your model can include a pretrained model inside, so that the forward of your whole model takes task id as argument but you don't forward it to the pretrained submodule. I think it depends on what you have to do here.
