### ISSUE TITLE
LwF and ewc issues with multi-head (SplitCIFAR10)

### ISSUE THREAD

**Issue by RgMoller** [ContinualAI/avalanche#722]
🐛 **Describe the bug**

LwF and EWC have issues with multi-head with CIFAR10. 

lwf - crashes with "AttributeError: 'NoneType' object has no attribute 'detach'"
ewc - performance worse than Naive

🐜 **To Reproduce**

https://gist.github.com/RgMoller/f814494b0ba46e80926e7bface5a02f4

🐝 **Expected behavior**
LwF - model shows decreased forgetting
ewc - model shows decreased forgetting

🐞 **Screenshots**

🦋 **Additional context**
Add any other context about the problem here like your python setup.

**Comment by Piyush-555** [comment]
EWC is not expected to perform well for datasets like SplitMNIST and SplitCIFAR10.
As for LwF, I'm getting a different error as follows:
```python
TypeError: forward() missing 1 required positional argument: 'task_labels'
```
Seems like multi-task support is not there for LwF.
@AntonioCarta is it okay, if I work on this?

**Comment by AntonioCarta** [comment]
Hi @Piyush-555, I'm currently working on this issue. I already identified the problem with both strategies and I partially fixed them.

Let me know if you want to work on something else. You can write me a private message on the ContinualAI slack and I can help you choose an appropriate issue.

**Comment by Piyush-555** [comment]
Sure
