### ISSUE TITLE
EWC online mode not working in some cases

### ISSUE THREAD

**Issue by AlbinSou** [ContinualAI/avalanche#744]
🐛 **Describe the bug**
EWC plugin is not working in online mode in some scenarios.

The online mode seems to work fine in the example ewc_mnist.py. However, in several projects of mine using other datasets and other kind of scenarios ( both nc_benchmark and ni_benchmark ), it does not work as expected.

🐜 **To Reproduce**

Inside the avalanche/examples/multihead.py, change the line 62 to:
```python
strategy = EWC(..., mode='online')
```
then run python multihead.py

The following error is raised in plugins/ewc.py, after starting training on the second task:

```
line 152: (k1, (self.decay_factor * old_imp + curr_imp))
TypeError: unsupported operand type for *: 'NoneType' and 'Tensor'
```

🐝 **Expected behavior**

Either an error message saying that this mode is not available if the scenario really does not fit this mode, or the normal working of the plugin in these situations.

**Comment by AntonioCarta** [comment]
It seems that you did not set `decay_factor`, which is needed tu run in the `online` mode. I'm adding a warning to catch these mistake at initialization time.
