### ISSUE TITLE
Question about replay

### ISSUE THREAD

**Issue by ashok-arjun** [ContinualAI/avalanche#767]
Hi,

I have a few questions about the replay algorithm implemented in avalanche, specifically the one that is used by calling `ReplayPlugin`.

1. If the memory size is 2000, why is there a need for 2000 samples in the very first task to fill the memory? Can the samples that are present be used, and can't the memory expand to a maximum of 2000 as tasks progress? I'm using a long-tailed dataset and some classes don't have 2000 samples.

**Comment by AntonioCarta** [comment]
This is a parameter that you can control when you initialize the replay buffer (`adaptive_size=True`). In general, using the max size at each step and subsampling to make space works slightly better (see Table 1 [here](https://arxiv.org/abs/2010.15277)).
