### ISSUE TITLE
Core50 benchmark with ICARL strategy

### ISSUE THREAD

**Issue by gab709** [ContinualAI/avalanche#774]
ICarl strategy returns an error  with Core50 benchmark:
`scenario = CORe50(scenario="nc", run=9)`

The error is:
`AttributeError: 'GenericCLScenario' object has no attribute 'n_classes_per_exp'`

Other nc benchmarks belong to "NCScenario"  class and this issue does not appear.

**Comment by ggraffieti** [comment]
Update: benchmarks created with the method `create_multi_dataset_generic_benchmark` have the same problem (no attribute `n_classes_per_exp` and `classes_order`. 
I did not investigate much, but seems that also benchmark created with `create_generic_benchmark_from_filelists` (as CORe50) have the same problem. 

Maybe is related to the generic benchmarks?

**Comment by ashok-arjun** [comment]
@ggraffieti I think it's related to how the structure of the generic benchmarks is. 

I'd like to take up this issue. You can assign it to me.

How might I approach it? @AntonioCarta @ggraffieti

**Comment by lantao1234** [comment]
When i create a paths_benchmark, the function have the same problem.

AttributeError: 'GenericCLScenario' object has no attribute 'n_classes_per_exp'

**Comment by ema-marconato** [comment]
Is still an open issue?

**Comment by Melika-Ayoughi** [comment]
I have the same problem with ego objects benchmark and icarl. Is it still not fixed?
