### ISSUE TITLE
Make some packages optional

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/avalanche#780]
We can wrap some `import` in a `try ... catch` statement so the user is not necessarily forced to install all the libraries, especially for the ones needed only by a specific strategy/logger.

e.g. quadprog, wandb, ...

**Comment by rokity** [comment]
Hi 

I suggest to make a refactor of the evaluation, logging, training and also models to check if some library are optional. If it's optional add a try and catch clause.

**Comment by AntonioCarta** [comment]
@ggraffieti as we discussed yesterday, I'm assigning this issue to you. Keep us updated!
