### ISSUE TITLE
Config type in WandBLogger

### ISSUE THREAD

**Issue by hamedhemati** [ContinualAI/avalanche#797]
This is more like a suggestion than a bug. The `config` parameter to the WandBLogger is supposed to be of type `args.namespace`. Therefore it converts it to a dictionary inside its `arge_parse` function using `vars(.)`. This might be restrictive in some cases if someone wants to pass configs directly as a dictionary (for example when hyperparameters are loaded from a YAML file). Wouldn't it be better to do the conversion outside the logger to make it more general in terms of config input?

Thanks :)

**Comment by AndreaCossu** [comment]
I agree, we can easily add support for plain dictionary. @digantamisra98 are you still working on the logger right? Can you take care of this?

**Comment by hamedhemati** [comment]
I've made a simple fix to it by removing the conversion inside WandBLogger. It works with plain dictionaries now. I also made a PR just in case.
