### ISSUE TITLE
EWCPlugin not working with customized benchmarks

### ISSUE THREAD

**Issue by hamedhemati** [ContinualAI/avalanche#821]
EWCPlugin's `compute_importances` function assumes that the data samples in the benchmark are always in the form (x, y, t). This breaks the dataloader when additional labels or attributes are present in each batch of data, for example when data samples are in the format (x, y, a1, a2, ..., t). I had this error when running EWC for a customized benchmark. I've made a small fix to the data loading part by treating each batch as a single tuple and only extracting (x, y, t) from it afterward.

**Comment by vlomonaco** [comment]
Thanks @hamedhemati!

**Comment by AntonioCarta** [comment]
FYI when you make a PR you can link issues so that they are closed automatically when the PR is merged (example: #821).
