### ISSUE TITLE
Avalanche API documentation - 404 error

### ISSUE THREAD

**Issue by Bontempogianpaolo1** [ContinualAI/avalanche#827]
🐛 **Describe the bug**
Following the instructions on the website I tried to click "Avalanche API Documentation" inside the section "Learn Avalanche in 5 minutes" but I obtained an 404 error. 
Maybe a deprecated reference?
![image](https://user-images.githubusercontent.com/28188499/141346401-2730b50a-ead8-46d8-ab9b-1aa1a67f8fe3.png)

**Comment by vlomonaco** [comment]
thanks for reporting it. It has been fixed! :)
