### ISSUE TITLE
Forward Transfer Metrics Issue

### ISSUE THREAD

**Issue by DannyFGitHub** [ContinualAI/avalanche#837]
🐛 **Describe the bug**
Will a foward transfer metric work with a Naive strategy?

    eval_plugin = EvaluationPlugin(
        accuracy_metrics(minibatch=True, epoch=True, experience=True, stream=True),
        loss_metrics(minibatch=True, epoch=True, experience=True, stream=True),
        timing_metrics(epoch=True),
        forgetting_metrics(experience=True, stream=True),
        bwt_metrics(experience=True, stream=True),
        cpu_usage_metrics(experience=True),
        confusion_matrix_metrics(num_classes=scenario.n_classes, save_image=False, stream=True),
        disk_usage_metrics(minibatch=True, epoch=True, experience=True, stream=True),
        forward_transfer_metrics(experience=True, stream=True),
        collect_all=True,  # this is default value anyway
        benchmark=scenario,
        loggers=[interactive_logger, text_logger, tb_logger]
    )

This evaluation plugin causes an error at the forward_transfer_metric

AssertionError: eval every > -1 to compute forward transfer

🐞 **Screenshots**
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/45392314/143474641-a7af792f-77ee-4097-b3af-9543033085eb.png">

🦋 **Additional context**
Python 3.9.2

**Comment by AntonioCarta** [comment]
You need to change `eval_every`, which is an argument of the constructor needed to call `eval` inside the training loop. 

Forward transfer needs these calls. If you set `eval_every = -1` the `eval` is disabled, which means the metric cannot be computed.

**Comment by DannyFGitHub** [comment]
Thank you Antonio,
would you be able to specify where you would typically provide the `eval_every` parameter, or where its mean to be changed? I haven't explicitly written `eval_every = -1` anywhere in my code, makes me think its being implicitly initialized as a default somewhere.

**Comment by DannyFGitHub** [comment]
I see, for anyone else with this issue:
`eval_every` is a parameter of strategies and defaults to `-1`. 
If not set, this issue will happen when using `foward_transfer_metrics`.

Thank you Antonio, I'm closing this issue.
