### ISSUE TITLE
speed up tests

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#851]
Most tests in Avalanche are integration tests and are using very expensive datasets (e.g. MNIST) with large networks and a high number of iterations. This is not needed for most tests, so there is space for a lot of speedup.

**Comment by rokity** [comment]
Hi
I suggest to implement test for every new feature . So in this way you don't need to use every datasets, but just the dataset that you need.
What you think?

**Comment by AntonioCarta** [comment]
The idea is to use only a small synthetic dataset with a small input, which does a minimal number of iterations.

**Comment by niniack** [comment]
Could you please point to an example of a test that is using an unnecessarily expensive dataset?

**Comment by AntonioCarta** [comment]
A good place to start may be `tests/training/test_strategies` and `tests/training/test_ar1`. These are integration tests, so it doesn't matter exactly what architecture, data or number of iterations they use. We can probably use very small models, a small number of iterations and epochs (>1) and so on.

**Comment by AntonioCarta** [comment]
I added conditional testing so that datasets tests are not executed anymore by the github CI. These tests are unlikely to break unless the datasets are changed. Tests are now 4 times faster. I'm closing the issue.
