### ISSUE TITLE
Refactoring needed in 'Without Avalanche' on Avalanche homepage

### ISSUE THREAD

**Issue by zalakbhalani** [ContinualAI/avalanche#860]
```
    train_data_loader = DataLoader(
        train_dataset, num_workers=num_workers, batch_size=train_mb_size)
    correct = 0
    for iteration, (test_mb_x, test_mb_y) in enumerate(test_data_loader):
```
There is a mistake in Gitbook in `Without Avalanche` tab. We need to replace `train` with `test` in these lines.

Here are reference lines from the Gitbook README.md file.
https://github.com/ContinualAI/avalanche/blob/b6e9239c1780d3847276cdae5bc8c21deae660af/docs/gitbook/README.md?plain=1#L183

https://github.com/ContinualAI/avalanche/blob/b6e9239c1780d3847276cdae5bc8c21deae660af/docs/gitbook/README.md?plain=1#L179

**Comment by vlomonaco** [comment]
Thanks @zalakbhalani for reporting it! We'll fix it asap!

**Comment by zalakbhalani** [comment]
I may help you with fixing that. Can you assign this issue to me?
