### ISSUE TITLE
Some question Training on dynamic module PNN

### ISSUE THREAD

**Issue by Anderson-Jane** [ContinualAI/avalanche#876]
Follow your tutorial, create the benchmark PermutedMNIST(3 experience) and train on PNNstrategy. 
![train code](https://user-images.githubusercontent.com/81062094/148875008-9d229d9e-6504-4456-93c5-21a7bbafd3c1.png)
However, during the second experience eval process, keyerror accured:
![error report](https://user-images.githubusercontent.com/81062094/148875490-5113b786-0c2c-41df-a414-d3edd7e2459b.png)
It should be the subscript overflow.What is the right way to train PNN?

**Comment by AntonioCarta** [comment]
thanks for the report. I will try to fix it asap. You are running the notebook without modification? If not, please give me a complete example

**Comment by Anderson-Jane** [comment]
Sorry for the late reply, here is the code I implemented:
![image](https://user-images.githubusercontent.com/81062094/150084348-37b87ef3-b16b-4d69-8838-d91e63a4c548.png)

**Comment by AntonioCarta** [comment]
Can you give me a text file that I can easily copy-paste? I need something that I can run myself to debug it quickly.

**Comment by Anderson-Jane** [comment]
```
import torch
from torch.optim import SGD
from torch.nn import CrossEntropyLoss
from avalanche.models import SimpleMLP, PNN
from avalanche.benchmarks.classic import  RotatedMNIST
from avalanche.training.strategies import PNNStrategy

model = PNN(num_layers=2, in_features=784, hidden_features_per_column=100, 
            adapter='mlp')
device = torch.device('cuda:0')
optimizer = SGD(model.parameters(), lr=0.001, momentum=0.9)
criterion = CrossEntropyLoss()
cl_strategy = PNNStrategy(num_layers=2, in_features=784, 
                          hidden_features_per_column=100,
                          lr=0.01,train_epochs=1, criterion=criterion,
                          train_mb_size=250,
                          eval_mb_size=250, device=device, adapter='mlp')

# scenario
benchmark = PermutedMNIST(n_experiences=3, seed=1)
# use GPU
device = torch.device('cuda:0')
# TRAINING LOOP
print('Starting experiment...')
results = []
for experience in benchmark.train_stream:
    print("Start of experience: ", experience.current_experience)
    print("Current Classes: ", experience.classes_in_this_experience)

    cl_strategy.train(experience)
    print('Training completed')

    print('Computing accuracy on the whole test set')
    results.append(cl_strategy.eval(benchmark.test_stream))

```

**Comment by AntonioCarta** [comment]
@Anderson-Jane this is fixed now.
