### ISSUE TITLE
OpenLORIS dataset auto-downloads on each code execution when using the classic scenario

### ISSUE THREAD

**Issue by tyler-hayes** [ContinualAI/avalanche#926]
🐛 **Describe the bug**
When trying to create the classic scenario for the OpenLORIS dataset, the download flag is set to True, which auto-downloads the dataset every time the script is run.

🐜 **To Reproduce**
```
from avalanche.benchmarks.classic import OpenLORIS


# creating the benchmark (scenario object)
scenario = OpenLORIS(dataset_root='/media/tyler/Data/datasets/OpenLORIS')
```

🐝 **Expected behavior**
The scenario loader would use the data located at `dataset_root` instead of auto-downloading the data each time the script is executed.

🦋 **Additional context**
In `classic/openloris.py` the download flag is set to True. Can this be changed so the data doesn't always download?

**Comment by AndreaCossu** [comment]
This is strange, the dataset should not be downloaded twice, even if `download=True`. It may be a bug related to the [`load_metadata`](https://github.com/ContinualAI/avalanche/blob/68ee2362204eff392d61ccca01155bade1e3be32/avalanche/benchmarks/datasets/openloris/openloris.py#L80) method in our OpenLoris implementation. It should check if the dataset is already present. If it returns `True` the download is not triggered.
Thanks for reporting we will look into that.

**Comment by tyler-hayes** [comment]
Perhaps the issue is that I downloaded the dataset from the project website directly and then tried using the `dataset_root` path to access the images. Downloading with python was very slow, whereas downloading from the project website was much quicker for some reason

**Comment by tyler-hayes** [comment]
It looks like I was missing the extra meta-data files (`batches_filelists.zip`, `Labels.pkl`, `LUP.pkl`, and `Paths.pkl`). Once I downloaded those and made my `dataset_root` a `Path` object from the `pathlib` library, the scenario successfully loaded. Sorry for the confusion and thanks for your quick reply and willingness to help! :D

**Comment by AndreaCossu** [comment]
No problem, thanks for getting in touch :smile: I'll close this issue then!
