### ISSUE TITLE
Could not use multiple workers for training on Windows

### ISSUE THREAD

**Issue by Servat0r** [ContinualAI/avalanche#930]
🐛 **Describe the bug**
Trying to run the example script on README.md on Windows 10 (with "if __name__ == '__main__'" line for running with PyCharm), if I set num_workers to a value > 0 in cl_strategy.train(...), I get the following error:

Traceback (most recent call last):
  File "C:\Users\Amministratore\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
TypeError: __init__() missing 1 required positional argument: 'avalanche_dataset'

Specifically, using PyCharm debugger I was able to depict this stack trace:
training_epoch, base_sgd.py:218
_train_exp, base_sgd.py:175
train, base.py:101
train, base_sgd.py:129
<module>, main.py:32

The program works well until that line, then it raises the above error.

🐜 **To Reproduce**

OS: Windows 10 Pro
IDE: PyCharm Community Edition 2021.2.3
Avalanche: source code got from third commit on March 1, 2022 "Merge pull request #924..."
Code:
import torch
from torch.nn import CrossEntropyLoss
from torch.optim import SGD

from avalanche.benchmarks.classic import PermutedMNIST
from avalanche.models import SimpleMLP
from avalanche.training.supervised import Naive

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

model = SimpleMLP(num_classes=10)

perm_mnist = PermutedMNIST(n_experiences=3)
train_stream = perm_mnist.train_stream
test_stream = perm_mnist.test_stream

optimizer = SGD(model.parameters(), lr=0.001, momentum=0.9)
criterion = CrossEntropyLoss()

cl_strategy = Naive(
    model, optimizer, criterion, train_mb_size=32, train_epochs=2,
    eval_mb_size=32, device=device)

if __name__ == '__main__':
    results = []
    for train_task in train_stream:
        cl_strategy.train(train_task, num_workers=4)
        results.append(cl_strategy.eval(test_stream))

🐝 **Expected behavior**
Expected to run without problems and display experiment results.

🐞 **Screenshots**
![image](https://user-images.githubusercontent.com/61659446/156923849-2f67022c-f5c1-409a-bfdf-5adac0dda218.png)
![image](https://user-images.githubusercontent.com/61659446/156923925-6f7d366d-d447-4b55-b88a-a7d9f2b39a88.png)

🦋 **Additional context**
IDE: PyCharm Community Edition 2021.2.3
Python Interpreter: Python 3.9.10

**Comment by AndreaCossu** [comment]
I think `num_workers>0` + Windows is a known bug. You can take a look at #249 which references this [pytorch bug](https://github.com/pytorch/pytorch/issues/12831).

**Comment by Servat0r** [comment]
@AndreaCossu 
self = reduction.pickle.load(from_parent)
TypeError: init() missing 1 required positional argument: '**_avalanche__**dataset'

The pytorch bug talks about very slow dataloaders, but this does not work.

**NOTE** : If num_workers>0 is on **test** set, it works fine.

I think it is Avalanche-related.

**Comment by AndreaCossu** [comment]
I think first we need to be able to reproduce this. Unfortunately I am not on Windows, maybe @vlomonaco or @AntonioCarta can give it a try.

**Comment by vlomonaco** [comment]
@Servat0r please check also if PR #938 helps!
