### ISSUE TITLE
Support tensorflow

### ISSUE THREAD

**Issue by 769430755** [ContinualAI/avalanche#952]
I use this repo to work with continual learning works recently, it helps me a lot.
And do you have any plan to support tensorflow(now is PyTorch), such as the class "model", which is implemented by torch.nn? 
Thank you!

**Comment by vlomonaco** [comment]
Hi, thanks, we don't have any short-term plans to support Tensorflow, sorry. A discussion about this here: https://github.com/ContinualAI/avalanche/discussions/497
