### ISSUE TITLE
"Least Astonishment" and ICaRLLossPlugin

### ISSUE THREAD

**Issue by lkorycki** [ContinualAI/avalanche#966]
Hello,

I was wondering if we can run iterative experiments with multiple streams/algorithms/parameters in one script when using this library. Was it considered in its design?

I am asking because most (all?) of the included examples show only a single run for a given algorithm and benchmark. There are no loops like:

```
for stream in streams:
   for param in [1,2,3]:
      learner = Learner(param)
      eval(learner, stream)
```

I would assume that we can write scripts like that, however, I encountered a very nasty behavior when trying to run some loops with ICaRL. 

The problem is with its constructor that sets `def __init__(self, ..., criterion=ICaRLLossPlugin()...)`. If we run some experiments iteratively, for example, using different streams in one script (as given above, when Learner=ICaRL), then it leads to the situation where `self.old_model` in the plugin **is not** `None` after we are done with one stream and move the next one - so it basically propagates the (old) model from the previous evaluation to the current one. It happens because `criterion` points to exactly the same `ICaRLLossPlugin` object even if we create two different ICaRL instances. 

It is a pretty well-known issue of the principle of the least astonishment that Python can very easily break if we use mutable default arguments (https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument). 

If the library should not be used in the given manner then it is not really a bug, but if there was no intention to impose such a limitation then it should be corrected.

Thanks!

**Comment by AntonioCarta** [comment]
You are correct, the mutable assignment in the constructor is a bug and it should be changed.

**Comment by lkorycki** [comment]
:+1: I think I can try taking care of it next month. It seems pretty easy to fix.

**Comment by AntonioCarta** [comment]
Thanks, I'm assigning this to you.

**Comment by AntonioCarta** [comment]
I think there may be other similar issues (e.g. the default logger). If you catch them, you can fix those too.

**Comment by lkorycki** [comment]
Sure :)
