### ISSUE TITLE
Avalache scripts are not returning to terminal prompt

### ISSUE THREAD

**Issue by TimmHess** [ContinualAI/avalanche#969]
🐛 **Describe the bug**
When execution of an avalanche-based (training) script is concluded (the last line of code is completed successfully) the script does not terminate but keeps 'idling', i.e. not returning to the terminal prompt. It is only after manual interference (Ctrl-C) that I reach the prompt again.

🐜 **To Reproduce**
For reproduction purposes I used this code: 
``` python
import avalanche as avl
from avalanche.benchmarks.generators import ni_benchmark
from avalanche.benchmarks.datasets import MNIST
from avalanche.models.simple_cnn import SimpleCNN

import torch
import torchvision.transforms as transforms

from datetime import datetime

device = 'cuda' if torch.cuda.is_available() else 'cpu'

"""
Load dataset
"""
train_MNIST = MNIST("./data/mnist/", train=True, download=True, transform=transforms.ToTensor())
test_MNIST = MNIST("./data/mnist/", train=False, download=True, transform=transforms.ToTensor())

"""
Generate scenario
"""
scenario = ni_benchmark(train_dataset=train_MNIST, test_dataset=test_MNIST, n_experiences=4,
    balance_experiences=True)

"""
Init Model
"""
model = SimpleCNN(num_classes=10)

"""
Init Optimizer
"""
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

""" 
Init Eval Plugin
"""
logging_dir = "./results/" + datetime.now().strftime("%Y.%m.%d-%H:%M") + "/"
eval_plugin = avl.training.plugins.EvaluationPlugin(
    avl.evaluation.metrics.loss_metrics(epoch=True, experience=True, stream=True),
    avl.evaluation.metrics.accuracy_metrics(epoch=True, experience=True, stream=True),
    avl.evaluation.metrics.forgetting_metrics(experience=True, stream=True),
    loggers=[avl.logging.InteractiveLogger(), avl.logging.TensorboardLogger(logging_dir)],
    benchmark=scenario)

"""
Init Training Strategy
"""
strategy = avl.training.Naive(model, optimizer, torch.nn.CrossEntropyLoss(), train_mb_size=32,
                              eval_mb_size=256, eval_every=-1, evaluator=eval_plugin, device=device,
                              train_epochs=10)

print("Code done...")
```

🐝 **Expected behavior**
After loading the dataset and doing some setups it will print the 'Code done...' to the terminal but not return the prompt. 

🦋 **Additional context**
I am using python 3.8.10 with avalanche 0.1.0 and torch 1.11.0 (Cuda 11.3)

**Comment by AntonioCarta** [comment]
I'm unable to reproduce this issue on the master branch. Can you check on the master branch?
On my system the script closes correctly.

**Comment by AndreaCossu** [comment]
I ran the script with Avalanche 0.1.0 and python 3.9.7 and also in my case it completes successfully.

**Comment by TimmHess** [comment]
Ok this is weird. I narrowed it down to the TensorboardLogger. The script exits to prompt as expected when I exclude the tb_logger or as well if I call `del` at the end of the script.  
Maybe it is something funny with my setup and tensorboard..

**Comment by AndreaCossu** [comment]
I reproduced the behavior with your configuration. It seems to be dependent on python version: code works on python 3.9.7 and torch 1.11.0. 
I don't know the reason behind it but if you don't want to switch to avalanche master branch one solution may be to upgrade python :smile:

**Comment by TimmHess** [comment]
Oh wow, nice :D Thank you for putting in the effort and testing that for me, much appreciated!
