### ISSUE TITLE
¿Running on GPU?

### ISSUE THREAD

**Issue by PabloMese** [ContinualAI/avalanche#981]
Hi everybody

How can I know if the experiments are running in the CPU or GPU? If by default is the CPU, how can I change it to run them in the GPU? 

```
print(torch.cuda.is_available())
True
```

Thank you in advance

**Comment by AntonioCarta** [comment]
Strategies have an argument `device`. Example:
```
strat = Naive(..., device='cuda')  # model will run on GPU
```
