### ISSUE TITLE
Problem in JointTraining strategy

### ISSUE THREAD

**Issue by evertonaleixo** [ContinualAI/avalanche#983]
Hi, I was looking at the JointTraining strategy training code, and it only considers the first experience. When I create a benchmark with more than one experience, it only trains on the first one.

I think I should aggregate the dataset from all experiments and then train the model.
Am I right?

🐜 **To Reproduce**
```
import torch.nn as nn

from torch.nn import CrossEntropyLoss
from torch.optim import SGD


from avalanche.evaluation.metrics import forgetting_metrics, accuracy_metrics, loss_metrics
from avalanche.evaluation.metrics import timing_metrics, cpu_usage_metrics
from avalanche.evaluation.metrics import confusion_matrix_metrics, disk_usage_metrics

from avalanche.benchmarks.classic import PermutedMNIST

from avalanche.models import SimpleCNN
from avalanche.logging import InteractiveLogger

from avalanche.training.plugins import EvaluationPlugin
from avalanche.training.strategies import Naive, JointTraining,BaseStrategy

device = "cuda"
modelUpper = SimpleCNN()
optimizerUpper = SGD(modelUpper.parameters(), lr=1e-3)
criterion = CrossEntropyLoss()

permutMnistBenchmark = PermutedMNIST(
  n_experiences=10,
  seed=1234,
)

upperBoundStrategy = JointTraining(
    modelUpper,
    optimizerUpper,
    criterion,
    train_mb_size=16,
    device=device,
    eval_mb_size=16,
    train_epochs=2,
    plugins=[],
)
upperBoundStrategy.evaluator.loggers = [InteractiveLogger()]

upperBoundStrategy.train(permutMnistBenchmark.train_stream)

```

🐝 **Expected behavior**
The training use all data sets of the benchmark.

**Comment by AndreaCossu** [comment]
Under the hood, `JointTraining` concatenates all the data in each training experience into a single dataset and trains the model on it. If you look at the progress bar during training is longer than the one of a single experience alone.

**Comment by evertonaleixo** [comment]
![image](https://user-images.githubusercontent.com/6534458/163443275-ccdd4b6b-c482-465f-9e6d-855cdaf9e30e.png)

I did it, but the amount of items in the data set is only 60.000 using 10 experiences. It should be 600.000.

**Comment by AntonioCarta** [comment]
Can you try the master branch? it seems fixed there.

**Comment by evertonaleixo** [comment]
I looked line by line and found my mistake. Despite the log only showing 60.000 items, it really merges the data of all data sets.

Thank you. I will close this thread.
